--
-- PostgreSQL database dump
--

\restrict j47voibEIHWbdcPzwvSEtwxmIWAuifofocBUJqqfNBS7NNnukA4XcZmhggdtip8

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.2

-- Started on 2026-08-22 17:22:51

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 20685)
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- TOC entry 5100 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 233 (class 1259 OID 21004)
-- Name: api_logs; Type: TABLE; Schema: public; Owner: cohort_user
--

CREATE TABLE public.api_logs (
    log_id integer NOT NULL,
    submission_id integer,
    section_key character varying(50),
    model_name character varying(100),
    prompt_sent text,
    response_received text,
    tokens_used integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.api_logs OWNER TO cohort_user;

--
-- TOC entry 232 (class 1259 OID 21003)
-- Name: api_logs_log_id_seq; Type: SEQUENCE; Schema: public; Owner: cohort_user
--

ALTER TABLE public.api_logs ALTER COLUMN log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_logs_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 20953)
-- Name: forms; Type: TABLE; Schema: public; Owner: cohort_user
--

CREATE TABLE public.forms (
    form_id integer NOT NULL,
    form_name character varying(255) NOT NULL,
    category character varying(100),
    is_active boolean DEFAULT true
);


ALTER TABLE public.forms OWNER TO cohort_user;

--
-- TOC entry 222 (class 1259 OID 20952)
-- Name: forms_form_id_seq; Type: SEQUENCE; Schema: public; Owner: cohort_user
--

ALTER TABLE public.forms ALTER COLUMN form_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 20971)
-- Name: questions; Type: TABLE; Schema: public; Owner: cohort_user
--

CREATE TABLE public.questions (
    question_id integer NOT NULL,
    section_id integer NOT NULL,
    v_code character varying(20) NOT NULL,
    variable_name character varying(100),
    question_text_fa text NOT NULL,
    response_type character varying(50) NOT NULL,
    coding_options jsonb,
    unit character varying(50),
    manual_prompt text,
    is_required boolean DEFAULT true,
    sort_order integer DEFAULT 0,
    group_pair character varying(100)
);


ALTER TABLE public.questions OWNER TO cohort_user;

--
-- TOC entry 226 (class 1259 OID 20970)
-- Name: questions_question_id_seq; Type: SEQUENCE; Schema: public; Owner: cohort_user
--

ALTER TABLE public.questions ALTER COLUMN question_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questions_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 20994)
-- Name: responses; Type: TABLE; Schema: public; Owner: cohort_user
--

CREATE TABLE public.responses (
    response_id integer NOT NULL,
    submission_id integer,
    question_id integer NOT NULL,
    v_code character varying(20),
    is_voice boolean DEFAULT true,
    transcript text,
    extracted_value text,
    extracted_value_json jsonb,
    ai_confidence double precision,
    processed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    group_index integer
);


ALTER TABLE public.responses OWNER TO cohort_user;

--
-- TOC entry 230 (class 1259 OID 20993)
-- Name: responses_response_id_seq; Type: SEQUENCE; Schema: public; Owner: cohort_user
--

ALTER TABLE public.responses ALTER COLUMN response_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.responses_response_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 20960)
-- Name: sections; Type: TABLE; Schema: public; Owner: cohort_user
--

CREATE TABLE public.sections (
    section_id integer NOT NULL,
    form_id integer NOT NULL,
    section_key character varying(50) NOT NULL,
    name_fa character varying(255) NOT NULL,
    sort_order integer DEFAULT 0,
    depends_on_vcode character varying(20),
    depends_on_value text,
    skip_if_vcode character varying(20),
    skip_if_value text
);


ALTER TABLE public.sections OWNER TO cohort_user;

--
-- TOC entry 224 (class 1259 OID 20959)
-- Name: sections_section_id_seq; Type: SEQUENCE; Schema: public; Owner: cohort_user
--

ALTER TABLE public.sections ALTER COLUMN section_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sections_section_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 20984)
-- Name: submissions; Type: TABLE; Schema: public; Owner: cohort_user
--

CREATE TABLE public.submissions (
    submission_id integer NOT NULL,
    user_id integer NOT NULL,
    form_id integer NOT NULL,
    status character varying(20) DEFAULT 'draft'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.submissions OWNER TO cohort_user;

--
-- TOC entry 228 (class 1259 OID 20983)
-- Name: submissions_submission_id_seq; Type: SEQUENCE; Schema: public; Owner: cohort_user
--

ALTER TABLE public.submissions ALTER COLUMN submission_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submissions_submission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 20945)
-- Name: users; Type: TABLE; Schema: public; Owner: cohort_user
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    first_name character varying(100),
    last_name character varying(100),
    national_code character varying(20) NOT NULL,
    phone_number character varying(20),
    role integer DEFAULT 1,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.users OWNER TO cohort_user;

--
-- TOC entry 220 (class 1259 OID 20944)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: cohort_user
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5094 (class 0 OID 21004)
-- Dependencies: 233
-- Data for Name: api_logs; Type: TABLE DATA; Schema: public; Owner: cohort_user
--

COPY public.api_logs (log_id, submission_id, section_key, model_name, prompt_sent, response_received, tokens_used, created_at) FROM stdin;
\.


--
-- TOC entry 5084 (class 0 OID 20953)
-- Dependencies: 223
-- Data for Name: forms; Type: TABLE DATA; Schema: public; Owner: cohort_user
--

COPY public.forms (form_id, form_name, category, is_active) FROM stdin;
1	پرسشنامه عمومی	general	t
2	پرسشنامه تغذیه	nutrition	t
3	پرسشنامه پزشکی	medical	t
\.


--
-- TOC entry 5088 (class 0 OID 20971)
-- Dependencies: 227
-- Data for Name: questions; Type: TABLE DATA; Schema: public; Owner: cohort_user
--

COPY public.questions (question_id, section_id, v_code, variable_name, question_text_fa, response_type, coding_options, unit, manual_prompt, is_required, sort_order, group_pair) FROM stdin;
1	1	A2	EnrollmentDate	تاریخ ثبت‌نام:	Date	\N	\N		t	1	\N
2	1	A3	CohortCenterID	مرکز کوهورت:	Categorical	{"2": "روانسر", "3": "گیلان", "4": "فسا", "5": "آذر", "6": "خرامه", "7": "مازندران", "8": "زاهدان", "9": "یزد", "10": "رفسنجان", "11": "هویزه", "12": "شهرکرد", "13": "بندرکنگ", "14": "دریاچه ارومیه", "15": "اردبیل", "16": "سبزوار", "17": "مشهد", "18": "دنا", "19": "کوار", "20": "دهقلان"}	\N		t	2	\N
3	1	A4	GenderID	جنسیت شما چیست؟	Categorical	{"1": "مرد", "2": "زن"}	\N		t	3	\N
4	1	A5	BirthDate	تاریخ تولد (طبق شناسنامه):	Date	\N	\N		t	4	\N
5	1	A26	MarriageNo	تعداد ازدواج:	Discrete	\N	بار		f	11	\N
6	1	A24	MaritalStatusID	وضعیت تأهل:	Categorical	{"1": "مجرد (ازدواج نکرده)", "2": "متأهل", "3": "همسر مرحوم/بیوه", "4": "مطلقه", "5": "سایر"}	\N		t	10	\N
7	1	A28	FamilyMarriageID	آیا ازدواج فامیلی بوده است؟	Categorical	{"1": "بله، فامیل درجه یک", "2": "خیر", "3": "بله، فامیل درجه دو"}	\N		f	13	\N
8	1	A30	ResidenceType	نوع محل سکونت:	Categorical	{"1": "شهری", "2": "روستایی"}	\N		t	14	\N
9	2	C1	HousingStatusID	وضعیت تملک مسکن:	Categorical	{"1": "ملک شخصی", "2": "ملک رهنی یا استیجاری", "3": "ملک سازمانی", "4": "ملک خویشاوندان (امانتی)"}	\N		t	1	\N
10	2	C4	FamilyNo	تعداد افرادی که با هم در منزل زندگی می‌کنید:	Discrete	\N	نفر		t	4	\N
11	2	C5	AccessFreezer	آیا فریزر جداگانه در اختیار دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	5	\N
12	2	C6	AccessWashingMachine	آیا ماشین لباسشویی در اختیار دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	6	\N
13	2	C7	AccessDishWasher	آیا ماشین ظرفشویی در اختیار دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	7	\N
14	2	C8	AccessComputer	آیا رایانه/لپ‌تاپ در اختیار دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	8	\N
15	2	C9	AccessInternet	آیا به اینترنت دسترسی دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	9	\N
16	2	C10	AccessMotorcycle	آیا موتورسیکلت در اختیار دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	10	\N
17	2	C11	AccessCar	آیا خودرو سواری در اختیار دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	11	\N
18	2	C12	CarPriceID	قیمت خودرو:	Categorical	{"1": "کمتر از ۲۰ میلیون تومان", "2": "۲۰-۵۰ میلیون تومان", "3": "۵۰-۱۰۰ میلیون تومان", "4": "بیشتر از ۱۰۰ میلیون تومان"}	\N		f	12	\N
19	2	C24	ForeignTravelNo	تعداد مسافرت‌های خارج از ایران (کل عمر):	Discrete	\N	مورد		f	14	\N
20	2	C25	ForeignPilgrimageNo	تعداد مسافرت‌های زیارتی خارج از ایران:	Discrete	\N	مورد		f	15	\N
21	2	C26	ForeignNonPilgrimageNo	تعداد مسافرت‌های غیر زیارتی خارج از ایران:	Discrete	\N	مورد		f	16	\N
22	3	E1	WaterSourceID1	منبع اصلی آب آشامیدنی شما چیست؟ (منبع اول)	Categorical	{"1": "آب چاه", "2": "آب رودخانه", "3": "آب چشمه", "4": "آب لوله کشی", "5": "آب معدنی", "6": "تانکر آب", "7": "آب انبار", "8": "سایر"}	\N		t	1	\N
23	3	E3	TapWaterAllTime	آیا همیشه از آب لوله کشی استفاده کرده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	2	\N
24	3	H3	FallingSleepDurationMin	از زمانی که به رختخواب می‌روید تا خوابتان ببرد چقدر طول می‌کشد؟	Discrete	\N	دقیقه		t	6	\N
25	3	H4	MorningWakeupHour	معمولاً صبح‌ها چه ساعتی بیدار می‌شوید؟ (ساعت)	Discrete	\N	ساعت		t	7	\N
26	3	H5	MorningWakeupMin	معمولاً صبح‌ها چه ساعتی بیدار می‌شوید؟ (دقیقه)	Discrete	\N	دقیقه		t	8	\N
27	3	H8	DayTimeNap	آیا در طول روز می‌خوابید؟ (سه بار یا بیشتر در هفته)	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	9	\N
28	3	H9	NapDurationMin	هر بار چند دقیقه می‌خوابید؟	Discrete	\N	دقیقه		f	10	\N
29	6	N1	DiseaseHxID	بیماری:	MultiSelect	{"1": "دیابت", "2": "فشار خون", "3": "بیماری قلبی", "4": "سکته قلبی", "5": "سکته مغزی", "6": "سرطان معده", "7": "سرطان کولورکتال", "8": "سرطان پستان", "9": "سرطان پروستات", "10": "سرطان پوست", "11": "سرطان مثانه", "12": "سرطان سیستم خونی", "13": "سرطان مری", "14": "سرطان ریه", "15": "سرطان مغز", "16": "صرع", "17": "اختلالات روانپزشکی", "18": "سردرد مزمن", "19": "آلزایمر", "20": "شکستگی لگن", "21": "سرطان حنجره", "22": "سرطان زبان", "23": "سرطان رحم", "24": "سرطان تخمدان", "25": "لوپوس", "26": "ام اس"}	\N		t	1	\N
30	3	H13	DozingOff	آیا در طول روز وقتی فعالیتی ندارید بدون اختیار چرت می‌زنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	12	\N
31	3	H14	SleepingPillsUse	آیا از داروهای خواب آور بطور مداوم استفاده می‌کنید؟ (بیشتر از ۲ بار در هفته)	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	13	\N
32	3	I1	MobileUse	آیا تلفن همراه دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	14	\N
33	3	E4	TapWaterUseYear	چند سال است که از آب لوله کشی استفاده می‌کنید؟	Continuous	\N	سال		f	3	\N
34	3	H1	NightSleepHour	معمولاً شب‌ها چه ساعتی می‌خوابید؟ (ساعت)	Discrete	\N	ساعت		t	4	\N
35	3	H2	NightSleepMin	معمولاً شب‌ها چه ساعتی می‌خوابید؟ (دقیقه)	Discrete	\N	دقیقه		t	5	\N
36	3	I2	MobileUseDuration	چند سال است که از تلفن همراه استفاده می‌کنید؟	Continuous	\N	سال		f	15	\N
37	3	J1	NearFarm	آیا منزل شما نزدیک مناطقی که در آن کشت و کار انجام می‌شود قرار دارد؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	16	\N
271	4	L52	SurgeryNo	تعداد دفعات جراحی:	Discrete	\N	بار	\N	f	52	\N
38	3	J2	FarmDistanceID	فاصله مزرعه تا منزل:	Categorical	{"1": "دور (بیشتر از ۲۰۰ متر)", "2": "تقریباً نزدیک (۱۰۰-۲۰۰ متر)", "3": "نزدیک (۵۰-۱۰۰ متر)", "4": "خیلی نزدیک (کمتر از ۵۰ متر)"}	\N		f	17	\N
39	3	J3	UseInFarm	آیا از سموم آفت‌کش در مزرعه، گلخانه یا زمین‌های کشاورزی استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	18	\N
40	3	J35	ManageSprayingPesticide	آیا مدیریت عملیات اسپری کردن سموم را بر عهده دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	20	\N
41	4	K1	HasDiabetes	آیا به دیابت مبتلا هستید؟	Categorical	{"0": "خیر", "1": "بله", "2": "نمی‌داند"}	\N		t	1	\N
42	4	K4	HasHypertension	آیا به فشار خون بالا مبتلا هستید؟	Categorical	{"0": "خیر", "1": "بله", "2": "نمی‌داند"}	\N		t	4	\N
43	4	K7	HasCardiacDisease	آیا به بیماری‌های ایسکمیک قلبی (نارسایی قلبی، آنژین) مبتلا هستید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	6	\N
44	4	K10	HasMI	آیا سابقه سکته قلبی دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	7	\N
45	4	K13	HasStroke	آیا سابقه سکته مغزی دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	8	\N
46	4	K16	HasRenalFailure	آیا به نارسایی کلیه مبتلا هستید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	9	\N
47	4	K19	HasFattyLiver	آیا به کبد چرب مبتلا هستید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	10	\N
48	4	K22	HasHepatitisB	آیا به هپاتیت B مبتلا هستید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	11	\N
49	4	K25	HasHepatitisC	آیا به هپاتیت C مبتلا هستید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	12	\N
50	4	K28	HasChronicLungDisease	آیا به بیماری‌های مزمن ریوی (سل/آسم) مبتلا هستید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	13	\N
51	4	K31	HasThyroidDisease	آیا به بیماری تیروئید مبتلا هستید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	14	\N
52	4	K34	HasKidneyStone	آیا سابقه سنگ کلیه دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	15	\N
53	4	K37	HasGallstone	آیا سابقه سنگ کیسه صفرا دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	16	\N
54	4	K40	HasRheumaticDisease	آیا به بیماری‌های روماتیسمی مبتلا هستید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	17	\N
55	4	K43	HasSkinCancer	آیا سابقه سرطان پوست دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	18	\N
56	4	K46	HasBreastCancer	آیا سابقه سرطان پستان دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	19	\N
57	4	K52	HasColorectalCancer	آیا سابقه سرطان کولورکتال دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	21	\N
58	4	K58	HasHSC	آیا سابقه سرطان سیستم هماتوپوئیتیک دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	23	\N
59	4	K61	HasEsophagealCancer	آیا سابقه سرطان مری دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	24	\N
60	4	K64	HasProstateCancer	آیا سابقه سرطان پروستات دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	25	\N
61	4	K67	HasLungCancer	آیا سابقه سرطان ریه دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	26	\N
62	4	K70	HasBrainAndCNSCancer	آیا سابقه سرطان مغز و اعصاب مرکزی دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	27	\N
64	4	K2	DiabetesStartAge	سن در زمان تشخیص دیابت:	Discrete	\N	سال		f	2	\N
65	4	K3	DiabetesInTreatment	آیا تحت درمان برای دیابت بوده/استید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	3	\N
66	5	Ma1	Anti_HTN_Drug	آیا از داروهای فشار خون استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	4	\N
67	4	K49	HasStomachCancer	آیا سابقه سرطان معده دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	20	\N
68	4	K55	HasBladderCancer	آیا سابقه سرطان مثانه دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	22	\N
69	5	Ma2	Anti_DM_Pills	آیا از داروهای خوراکی دیابت استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	5	\N
70	5	Ma3	Insulin	آیا از انسولین استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	6	\N
71	5	Ma4	Statins	آیا از استاتین‌ها استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	7	\N
72	6	N2	HasDisease	آیا فردی از خانواده به این بیماری مبتلا است؟	Categorical	{"0": "خیر", "1": "بله", "2": "نمی‌داند"}	\N		t	2	\N
73	6	N3	FamilyRelationID	نسبت فامیلی با بیمار:	Categorical	{"1": "پدر", "2": "مادر", "3": "برادر", "4": "خواهر", "5": "برادر ناتنی", "6": "خواهر ناتنی", "7": "پسر", "8": "دختر", "9": "پدربزرگ/مادربزرگ", "10": "همسر", "11": "سایر خویشاوندان درجه دو"}	\N		f	3	\N
74	7	O1	HasMenstruation	آیا تاکنون قاعده شده‌اید؟	Categorical	{"0": "خیر", "1": "بله"}	\N		t	1	\N
75	7	O2	MenstruationStartAge	سن شروع قاعدگی:	Discrete	\N	سال		f	2	\N
76	7	O3	NowPregnant	آیا در حال حاضر باردار هستید؟	Categorical	{"1": "بله", "2": "خیر", "3": "نمی‌داند"}	\N		t	3	\N
77	7	O4	PregnancyNo	تعداد حاملگی‌های قبلی:	Discrete	\N	مورد		f	4	\N
78	7	O5	FirstPregnancyAge	سن در زمان اولین حاملگی:	Discrete	\N	سال		f	5	\N
79	7	O6	AliveChildbirthNo	تعداد زایمان‌های با نوزاد زنده:	Discrete	\N	مورد		f	6	\N
80	7	O7	FirstAliveChildbirthAge	سن در زمان اولین تولد نوزاد زنده:	Discrete	\N	سال		f	7	\N
81	7	O8	HasStillbirth	آیا سابقه مرده‌زایی دارید؟	Categorical	{"0": "خیر", "1": "بله"}	\N		f	8	\N
82	7	O9	AbortionNo	تعداد سقط:	Discrete	\N	مورد		f	9	\N
83	7	O10	FirstAbortionAge	سن در زمان اولین سقط:	Discrete	\N	سال		f	10	\N
84	7	O11	BreastfeedingDuration	مجموع مدت شیردهی:	Continuous	\N	ماه		f	11	\N
85	7	O12	HasInfertility	آیا سابقه نازایی دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	12	\N
86	7	O14	OvaryRemovalTypeID	آیا سابقه برداشتن تخمدان دارید؟	Categorical	{"1": "بله، یک طرفه", "2": "بله، دو طرفه", "3": "خیر"}	\N		f	13	\N
87	7	O16	HasTubectomy	آیا سابقه توبکتومی دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	14	\N
88	7	O17	HasHysterectomy	آیا سابقه هیسترکتومی دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	15	\N
89	7	Oa3	ContraceptionTypeID	روش پیشگیری از بارداری:	Categorical	{"1": "قرص‌های پیشگیری", "2": "ایمپلنت", "3": "تزریق پروژسترون طولانی مدت", "4": "وسایل داخل رحمی (IUD)"}	\N		f	16	\N
90	8	B3	WaistCircumference	دور کمر:	Continuous	\N	سانتی متر		t	3	\N
91	8	B4	HipCircumference	دور باسن:	Continuous	\N	سانتی متر		t	4	\N
93	10	G18	AerobicExercise1	پیاده‌روی سریع، ورزش آئروبیک سبک:	Continuous	\N	ساعت		t	9	\N
94	10	G21	HeavyLaborAgricultJobs1	فعالیت‌های سنگین کارگری/کشاورزی:	Continuous	\N	ساعت		t	10	\N
95	10	G22	HeavyExercise1	فعالیت‌های ورزشی حرفه‌ای:	Continuous	\N	ساعت		t	11	\N
96	10	G23	Duration1	تعداد ماه‌هایی که این الگوی فعالیت را دارید:	Discrete	\N	ماه در سال		t	12	\N
97	11	H6	PreferredWakeupHour	دوست دارید صبح‌ها چه ساعتی بیدار شوید؟ (ساعت)	Discrete	\N	ساعت		t	1	\N
98	11	H7	PreferredWakeupMin	دوست دارید صبح‌ها چه ساعتی بیدار شوید؟ (دقیقه)	Discrete	\N	دقیقه		t	2	\N
99	11	H12	LegRestlessnessID	آیا در طول خواب پاهایتان زیاد حرکت می‌کند؟	Categorical	{"1": "بله", "2": "خیر", "3": "نمی‌دانم"}	\N		t	3	\N
100	12	Q1	BrushingNoID	دفعات مسواک زدن دندان‌ها:	Categorical	{"1": "یک بار در روز", "2": "دو بار در روز", "3": "سه بار در روز", "4": "سایر", "5": "مسواک نمی‌زنم", "6": "دندان مصنوعی دارم"}	\N		t	1	\N
101	8	B5	WristCircumference	دور مچ:	Continuous	\N	سانتی متر		f	5	\N
102	10	G1	SleepDuration24h1	خواب شبانه (متوسط):	Continuous	\N	ساعت		t	1	\N
103	10	G2	SleepDurationMidDay1	خواب عصر/میان‌روز:	Continuous	\N	ساعت		t	2	\N
104	10	G4	TV1	تماشای تلویزیون/فیلم/گوش دادن به موسیقی:	Continuous	\N	ساعت		t	3	\N
105	10	G5	Study1	مطالعه کتاب/مجله/روزنامه:	Continuous	\N	ساعت		t	4	\N
106	10	G8	Eating1	غذا خوردن، نشستن در جلسات/مهمانی‌ها:	Continuous	\N	ساعت		t	5	\N
107	10	G11	Cooking1	آشپزی، شستن ظروف، فعالیت‌های ایستاده:	Continuous	\N	ساعت		t	6	\N
108	10	G12	HouseCleaning1	نظافت منزل، شستن لباس، جارو کشیدن:	Continuous	\N	ساعت		t	7	\N
109	10	G14	Walking1	پیاده‌روی آهسته، پایین رفتن از پله:	Continuous	\N	ساعت		t	8	\N
110	12	Q2	TeethNo	تعداد کل دندان‌ها:	Discrete	\N	دندان		t	2	\N
111	12	Q3	DecayedTeethNo	تعداد دندان‌های پوسیده:	Discrete	\N	دندان		t	3	\N
112	12	Q4	MissingTeethNo	تعداد دندان‌های کشیده شده:	Discrete	\N	دندان		t	4	\N
113	12	Q5	FilledTeeth	تعداد دندان‌های پر شده:	Discrete	\N	دندان		t	5	\N
114	12	Q6	HasOralLesion	آیا ضایعه یا زخمی در دهان وجود دارد؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	6	\N
115	12	Q7	UseFlossing	آیا از نخ دندان استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	7	\N
116	12	Q8	FlossingNo	چند بار در هفته از نخ دندان استفاده می‌کنید؟	Discrete	\N	بار در هفته		f	8	\N
117	12	Q9	HasDentures	آیا دندان مصنوعی دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	9	\N
118	12	Q10	FromWhenDentures	از چه سنی دندان مصنوعی دارید؟	Discrete	\N	سالگی		f	10	\N
119	12	Q12	UseMouthwash	آیا از دهانشویه استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	11	\N
120	13	R1	SmokeCigaretteTypeID	آیا در طول زندگی حداقل ۱۰۰ نخ سیگار کشیده‌اید؟	Categorical	{"1": "بله", "2": "خیر"}	\N		t	1	\N
121	13	R2	FirstCigaretteAge	اولین سیگار را در چه سنی کشیدید؟	Discrete	\N	سالگی		f	2	\N
122	13	R3	RegularCigaretteAge	سیگار را به طور منظم از چه سنی شروع کردید؟	Discrete	\N	سالگی		f	3	\N
123	13	R4	CurrentSmokingTypeID	آیا هم اکنون سیگار می‌کشید؟	Categorical	{"1": "بله، روزانه", "2": "گاهی اوقات", "3": "خیر"}	\N		t	4	\N
124	13	R5	SmokingNo	به طور متوسط چند بار در شبانه‌روز سیگار می‌کشید؟	Discrete	\N	بار		f	5	\N
125	13	R6	StopSmokingAge	از چه سنی سیگار کشیدن روزانه را متوقف کرده‌اید؟	Discrete	\N	سالگی		f	6	\N
126	13	R9	SmokeInHomeNo	چند ساعت در روز در تماس با دود سیگار در منزل هستید؟	Continuous	\N	ساعت در روز		f	8	\N
127	13	R10	SmokeInWorkplaceID	آیا در محل کار در تماس با دود سیگار هستید؟	Categorical	{"1": "بله", "2": "خیر"}	\N		f	9	\N
128	13	R12	UseNonCigTobacco	آیا تاکنون از محصولات دخانی غیر سیگار (ناس، قلیان، چپق) استفاده کرده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	10	\N
129	14	R13	UseDrugs	آیا تاکنون از مواد مخدر استفاده کرده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	1	\N
130	14	Rc3	DrugTypeID	نوع ماده مخدر:	Categorical	{"1": "تریاک", "2": "هروئین", "3": "سوخته", "4": "شیره", "5": "شیشه", "6": "کوکائین", "7": "کراک", "8": "کریستال", "9": "پان", "10": "سایر"}	\N		f	2	\N
131	14	R14	UseAlcohol	آیا تاکنون از مشروبات الکلی استفاده کرده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	4	\N
132	14	Rd3	AlcoholTypeID	نوع مشروبات الکلی:	Categorical	{"1": "آبجو", "2": "مشروبات با الکل بالا (۴۰٪ و دکا، ویسکی، جین)", "3": "مشروبات دست ساز", "4": "سایر"}	\N		f	5	\N
133	14	Rc4	DrugUseTypeID	روش مصرف:	Categorical	{"1": "خوراکی", "2": "استنشاقی", "3": "تزریقی"}	\N		f	3	\N
134	15	S1	RightDBP1	فشار خون دیاستولیک - بازوی راست (اندازه‌گیری اول):	Discrete	\N	میلیمتر جیوه		t	1	\N
135	15	S2	RightDBP2	فشار خون دیاستولیک - بازوی راست (اندازه‌گیری دوم):	Discrete	\N	میلیمتر جیوه		t	2	\N
136	15	S3	RightSBP1	فشار خون سیستولیک - بازوی راست (اندازه‌گیری اول):	Discrete	\N	میلیمتر جیوه		t	3	\N
137	15	S4	RightSBP2	فشار خون سیستولیک - بازوی راست (اندازه‌گیری دوم):	Discrete	\N	میلیمتر جیوه		t	4	\N
138	15	S5	LeftDBP1	فشار خون دیاستولیک - بازوی چپ (اندازه‌گیری اول):	Discrete	\N	میلیمتر جیوه		t	5	\N
139	15	S6	LeftDBP2	فشار خون دیاستولیک - بازوی چپ (اندازه‌گیری دوم):	Discrete	\N	میلیمتر جیوه		t	6	\N
140	15	S7	LeftSBP1	فشار خون سیستولیک - بازوی چپ (اندازه‌گیری اول):	Discrete	\N	میلیمتر جیوه		t	7	\N
141	15	S8	LeftSBP2	فشار خون سیستولیک - بازوی چپ (اندازه‌گیری دوم):	Discrete	\N	میلیمتر جیوه		t	8	\N
142	15	S9	PR1	تعداد ضربان قلب در حالت استراحت (اندازه‌گیری اول):	Discrete	\N	ضربان در دقیقه		t	9	\N
143	15	S10	PR2	تعداد ضربان قلب در حالت استراحت (اندازه‌گیری دوم):	Discrete	\N	ضربان در دقیقه		t	10	\N
144	16	X1	HasUrine	آیا نمونه ادرار گرفته شد؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	1	\N
145	16	X2	HasBlood	آیا نمونه خون گرفته شد؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	2	\N
146	16	X3	HasHair	آیا نمونه مو گرفته شد؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	3	\N
147	16	X4	HasNail	آیا نمونه ناخن گرفته شد؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	4	\N
148	4	L6	HasHeartburn	آیا در یک سال گذشته دچار سوزش سردل شده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	28	\N
149	4	L7	HeartburnFrequencyOfOccurrence	تعداد دفعات سوزش سردل:	Categorical	{"1": "تقریباً هر روز", "2": "چند بار در ماه", "3": "چند بار در هفته", "4": "گاهی"}	\N		f	29	\N
150	4	L10	HasGERD	آیا تاکنون تشخیص بیماری رفلاکس اسید معده داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	30	\N
151	4	L11	HasBloating	آیا در یک سال گذشته دچار نفخ و اتساع شکم شده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	31	\N
152	4	L15	HasBloodInStool	آیا سابقه دفع خون تازه در مدفوع داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	32	\N
153	4	L16	HasUnintentionalWeightLoss	آیا سابقه کاهش وزن ناخواسته داشته‌اید؟ (بدون رژیم و بیش از ۵ کیلوگرم در یک ماه)	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	33	\N
154	4	L17	HasJaundice	آیا سابقه زردی چشم یا پوست بدن داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	34	\N
155	4	L19	HasFracture	آیا در سال اخیر هرگونه شکستگی داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	35	\N
156	4	L21	HasOsteoporosis	آیا تاکنون تشخیص پوکی استخوان داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	36	\N
157	4	L22	HasLowBackPain	آیا سابقه کمردرد داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	37	\N
158	4	L53	HasTransfusion	آیا سابقه ترانسفیوژن (تزریق خون) داشته‌اید؟	Categorical	{"1": "بله", "2": "خیر", "3": "نمی‌دانم"}	\N		t	38	\N
159	4	L55	DrugAllergy	آیا به داروی خاصی حساسیت دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	39	\N
160	9	U10	ReUseOil	آیا روغن پس از سرخ کردن را دوباره استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	17	\N
161	9	U12	ReUseMold	اگر غذایی مثل رب، مربا، ترشی کپک زده بود، قسمتی از آن را برداشته و بقیه را مصرف می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	18	\N
162	9	U13	SmokedFoodIntID	آیا از غذاهای دودی (برنج دودی، ماهی دودی) استفاده می‌کنید؟	Categorical	{"0": "هرگز", "1": "کمتر از ۱-۳ بار در ماه", "2": "۱-۳ بار در هفته", "3": "روزانه"}	\N		t	19	\N
163	9	U20	TeaTempUseID	چای و قهوه را با چه دمایی می‌خورید؟	Categorical	{"1": "داغ", "2": "گرم (وارم)", "3": "سرد", "4": "مصرف نمی‌کند"}	\N		t	20	\N
164	9	U21	SoupTempUseID	سوپ، آش و سایر غذاهای آبکی را با چه دمایی می‌خورید؟	Categorical	{"1": "داغ", "2": "گرم (وارم)", "3": "سرد", "4": "مصرف نمی‌کند"}	\N		t	21	\N
165	9	U43	UseBoiledHerbal	آیا از دمنوش‌های داروهای گیاهی، عرقیجات و یا پودرهای گیاهی استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	22	\N
166	8	B1	HeightCm	قد چند سانتی متر است	Continuous	\N	سانتی متر		t	1	\N
167	8	B2	WeightKg	وزن:	Continuous	\N	کیلوگرم		t	2	\N
168	1	A8	MotherEthnicityID	قومیت مادر:	Categorical	{"1": "فارس", "2": "آذری", "3": "بلوچ", "4": "کرد", "5": "لر", "6": "عرب", "7": "ترکمن", "8": "تالش", "9": "زابلی", "10": "گیلک", "11": "ترک ایل", "12": "عرب ایل", "13": "مازنی", "14": "توت", "15": "سایر", "16": "ترک"}	\N		f	5	\N
169	1	A10	FatherEthnicityID	قومیت پدر:	Categorical	{"1": "فارس", "2": "آذری", "3": "بلوچ", "4": "کرد", "5": "لر", "6": "عرب", "7": "ترکمن", "8": "تالش", "9": "زابلی", "10": "گیلک", "11": "ترک ایل", "12": "عرب ایل", "13": "مازنی", "14": "توت", "15": "سایر", "16": "ترک"}	\N		f	6	\N
170	1	A20	EducationYears	تعداد سال‌های تحصیل:	Discrete	\N	سال		t	7	\N
171	1	A21	LastEduID	آخرین مدرک تحصیلی:	Categorical	{"1": "ابتدایی", "2": "راهنمایی", "3": "دیپلم", "4": "فوق دیپلم", "5": "لیسانس", "6": "فوق لیسانس", "7": "دکترا", "8": "بی سواد"}	\N		t	8	\N
172	1	A22	FamilyStatusID	موقعیت شما در خانواده:	Categorical	{"1": "پدر", "2": "مادر", "3": "فرزند", "4": "پدربزرگ/مادربزرگ", "5": "عمه/عمو", "6": "خاله/دایی", "7": "سایر"}	\N		t	9	\N
173	9	U2	SaltUseID	آیا به غذای خود نمک اضافه می‌کنید؟	Categorical	{"1": "بله", "2": "گاهی", "3": "خیر"}	\N		t	12	\N
174	2	C2	HouseArea	متراژ واحد مسکونی:	Continuous	\N	متر مربع		t	2	\N
175	2	C3	HouseroomNo	تعداد اتاق‌های خواب:	Discrete	\N	اتاق		t	3	\N
176	2	C23	BookNoRead	تعداد کتاب‌های غیر درسی که در یک سال گذشته مطالعه کرده‌اید:	Discrete	\N	کتاب		f	13	\N
177	2	C27	NationalTravelNo	تعداد مسافرت‌های داخل ایران در ده سال گذشته:	Discrete	\N	مورد		f	17	\N
178	3	H10	NightShiftWork	آیا در طول یک سال گذشته کار شبانه داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	11	\N
179	3	J11	UseInHome	آیا از حشره‌کش در خانه استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		f	19	\N
180	9	T1	Bread_Lavash	نان لواش:	Continuous	\N	گرم در روز		f	1	\N
181	9	T5	Cooked_rice	برنج پخته:	Continuous	\N	گرم در روز		f	2	\N
182	9	T15	Red_meat	گوشت قرمز:	Continuous	\N	گرم در روز		f	3	\N
183	9	T16	Chicken	گوشت مرغ:	Continuous	\N	گرم در روز		f	4	\N
184	9	T18	Eggs	تخم مرغ:	Continuous	\N	گرم در روز		f	5	\N
185	9	T28	Milk	شیر:	Continuous	\N	گرم در روز		f	6	\N
186	9	T29	Yogurt	ماست:	Continuous	\N	گرم در روز		f	7	\N
187	9	T30	Cheese	پنیر:	Continuous	\N	گرم در روز		f	8	\N
188	9	T31	Doogh	دوغ:	Continuous	\N	گرم در روز		f	9	\N
189	9	T113	Salt	نمک:	Continuous	\N	گرم در روز		f	10	\N
190	1	A27	FirstMarriageAge	سن در زمان اولین ازدواج:	Discrete	\N	سال		f	12	\N
191	4	K5	HypertensionStartAge	سن در زمان تشخیص فشار خون بالا:	Discrete	\N	سال		f	5	\N
192	13	R8	SmokeInHome	آیا در معرض تماس با دود سیگار در منزل بوده/هستید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	7	\N
193	9	U1	EatIntID	به طور متوسط چند وعده غذا در روز می‌خورید؟	Categorical	{"1": "۳ وعده (صبحانه، ناهار، شام)", "2": "۴ وعده", "3": "۵-۶ وعده", "4": "بیشتر از ۶ وعده", "5": "کمتر از ۳ وعده"}	\N		t	11	\N
194	9	U3	FoodSaltUsedID	غذایی که می‌خورید چقدر شور است؟	Categorical	{"1": "کم نمک", "2": "معمولی", "3": "شور"}	\N		t	13	\N
195	9	U4	GrilledFoodIntID	چند وقت یکبار غذای کبابی مصرف می‌کنید؟	Categorical	{"0": "هرگز", "1": "کمتر از یک بار در ماه", "2": "۱-۳ بار در ماه", "3": "۱-۳ بار در هفته", "4": "روزانه"}	\N		t	14	\N
196	9	U5	FriedFoodIntID	چند وقت یکبار غذای سرخ شده مصرف می‌کنید؟	Categorical	{"0": "هرگز", "1": "کمتر از یک بار در ماه", "2": "۱-۳ بار در ماه", "3": "۱-۳ بار در هفته", "4": "روزانه"}	\N		t	15	\N
197	9	U9	UsedOilTypeID	چه نوع روغنی برای سرخ کردن استفاده می‌کنید؟	Categorical	{"1": "روغن جامد (دنبه/کره)", "2": "روغن نیمه جامد (مارگارین)", "3": "روغن مایع", "4": "روغن مخصوص سرخ کردنی", "5": "سایر", "6": "سرخ کردن انجام نمی‌دهم"}	\N		t	16	\N
198	3	EA3	AnimalContactLevelTypeID	سطح تماس با حیوانات:	Categorical	{"1": "بعضی مواقع (محل نگهداری حیوانات در ۲۰۰ متری محل کار یا زندگی)", "2": "حداقل یک بار در دو هفته ولی کمتر از یک بار در روز", "3": "تماس روزانه (نگهداری حیوانات در محل کار یا زندگی)", "4": "تماس روزانه و نزدیک (شغل‌های مربوط به تغذیه و تمیز کردن حیوانات)"}	\N	\N	f	21	\N
199	3	EA4	AnimalTypeID	نوع حیوان:	Categorical	{"1": "اسب سانان (اسب، قاطر، الاغ، شتر)", "2": "نشخوارکنندگان (گوسفند، بز، گاو)", "3": "سگ", "4": "طیور", "5": "گربه", "6": "سایر"}	\N	\N	f	22	\N
200	9	V1	Water_inSummer	میزان آب مصرفی در تابستان:	Discrete	\N	لیوان	(هر لیوان معادل ۲۳۰ میلی‌لیتر)	t	23	\N
201	9	V2	Water_SummerInterval	بازه زمانی مصرف آب در تابستان:	Categorical	{"1": "در روز", "2": "در هفته", "3": "در ماه"}	\N	\N	t	24	\N
202	9	V3	Water_inOther	میزان آب مصرفی در سایر فصل‌ها:	Discrete	\N	لیوان	(هر لیوان معادل ۲۳۰ میلی‌لیتر)	t	25	\N
203	9	V4	Water_OtherInterval	بازه زمانی مصرف آب در سایر فصل‌ها:	Categorical	{"1": "در روز", "2": "در هفته", "3": "در ماه"}	\N	\N	t	26	\N
204	9	W1	SupMultiVitaminMineralInterval	مولتی‌ویتامین و مینرال:	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	f	27	\N
205	9	W3	SupMultiVitaminInterval	مولتی‌ویتامین:	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	f	29	\N
206	9	W5	SupCalciumDInterval	کلسیم + ویتامین D:	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	f	31	\N
207	9	W7	SupCalciumInterval	کلسیم:	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	f	33	\N
208	9	W9	SupVitaminDPillInterval	ویتامین D (قرص):	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	f	35	\N
209	9	W11	SupVitaminDValInterval	ویتامین D (آمپول):	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	f	37	\N
210	9	F11_6	FolicAcid	اسیدفولیک:	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	f	38	\N
211	9	F11_7	Omega3	روغن ماهی / امگا ۳:	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	f	39	\N
212	9	F11_8	Iron	آهن:	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	f	40	\N
213	9	F11_9	Zinc	روی یا زینک:	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	f	41	\N
214	9	U22	WaterContainerTypeID1	از چه نوع ظروفی برای نگهداری آب استفاده می‌کنید؟ (نوع اول)	Categorical	{"1": "پلاستیکی", "2": "استیل", "3": "چینی", "4": "شیشه‌ای", "5": "سایر"}	\N	\N	t	42	\N
215	9	U23	WaterContainerTypeID2	از چه نوع ظروفی برای نگهداری آب استفاده می‌کنید؟ (نوع دوم)	Categorical	{"1": "پلاستیکی", "2": "استیل", "3": "چینی", "4": "شیشه‌ای", "5": "سایر"}	\N	\N	f	43	\N
216	9	U24	BreadContainerTypeID1	از چه نوع ظروفی برای نگهداری نان استفاده می‌کنید؟ (نوع اول)	Categorical	{"1": "پلاستیکی", "2": "استیل", "3": "پارچه‌ای", "4": "شیشه‌ای", "5": "سایر", "6": "نان نگهداری نمی‌کنم"}	\N	\N	t	44	\N
217	9	U25	BreadContainerTypeID2	از چه نوع ظروفی برای نگهداری نان استفاده می‌کنید؟ (نوع دوم)	Categorical	{"1": "پلاستیکی", "2": "استیل", "3": "پارچه‌ای", "4": "شیشه‌ای", "5": "سایر", "6": "نان نگهداری نمی‌کنم"}	\N	\N	f	45	\N
218	9	U26	LemonContainerTypeID1	از چه نوع ظروفی برای نگهداری آبلیمو و آبغوره استفاده می‌کنید؟ (نوع اول)	Categorical	{"1": "پلاستیکی", "2": "استیل", "4": "شیشه‌ای", "5": "سایر", "6": "نگهداری نمی‌کنم"}	\N	\N	t	46	\N
219	9	U27	LemonContainerTypeID2	از چه نوع ظروفی برای نگهداری آبلیمو و آبغوره استفاده می‌کنید؟ (نوع دوم)	Categorical	{"1": "پلاستیکی", "2": "استیل", "4": "شیشه‌ای", "5": "سایر", "6": "نگهداری نمی‌کنم"}	\N	\N	f	47	\N
220	9	U28	TomatoContainerTypeID1	از چه نوع ظروفی برای نگهداری رب و آب گوجه فرنگی استفاده می‌کنید؟ (نوع اول)	Categorical	{"1": "پلاستیکی", "2": "استیل", "4": "شیشه‌ای", "5": "سایر", "6": "نگهداری نمی‌کنم"}	\N	\N	t	48	\N
221	9	U29	TomatoContainerTypeID2	از چه نوع ظروفی برای نگهداری رب و آب گوجه فرنگی استفاده می‌کنید؟ (نوع دوم)	Categorical	{"1": "پلاستیکی", "2": "استیل", "4": "شیشه‌ای", "5": "سایر", "6": "نگهداری نمی‌کنم"}	\N	\N	f	49	\N
222	9	U30	PicklesContainerTypeID1	از چه نوع ظروفی برای نگهداری ترشی و خیارشور استفاده می‌کنید؟ (نوع اول)	Categorical	{"1": "پلاستیکی", "2": "استیل", "4": "شیشه‌ای", "5": "سایر", "6": "نگهداری نمی‌کنم"}	\N	\N	t	50	\N
223	9	U31	PicklesContainerTypeID2	از چه نوع ظروفی برای نگهداری ترشی و خیارشور استفاده می‌کنید؟ (نوع دوم)	Categorical	{"1": "پلاستیکی", "2": "استیل", "4": "شیشه‌ای", "5": "سایر", "6": "نگهداری نمی‌کنم"}	\N	\N	f	51	\N
224	9	U32	CookingWareID1	از چه نوع ظروفی برای پخت و پز استفاده می‌کنید؟ (نوع اول)	Categorical	{"1": "روکش روی", "2": "مسی", "3": "آلومینیومی", "4": "لعابی", "5": "تفلون", "6": "چدنی", "7": "استیل", "8": "پیرکس", "9": "سایر"}	\N	\N	t	52	\N
225	9	U33	CookingWareID2	از چه نوع ظروفی برای پخت و پز استفاده می‌کنید؟ (نوع دوم)	Categorical	{"1": "روکش روی", "2": "مسی", "3": "آلومینیومی", "4": "لعابی", "5": "تفلون", "6": "چدنی", "7": "استیل", "8": "پیرکس", "9": "سایر"}	\N	\N	f	53	\N
226	9	U34	CookingWareID3	از چه نوع ظروفی برای پخت و پز استفاده می‌کنید؟ (نوع سوم)	Categorical	{"1": "روکش روی", "2": "مسی", "3": "آلومینیومی", "4": "لعابی", "5": "تفلون", "6": "چدنی", "7": "استیل", "8": "پیرکس", "9": "سایر"}	\N	\N	f	54	\N
227	9	U35	UsedScratchedTeflon	آیا از ظروف تفلون که سطوحشان خراش دارد استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	55	\N
228	9	U36	EatingDishtwareID1	در چه ظروفی غذا می‌خورید؟ (نوع اول)	Categorical	{"1": "چینی", "2": "آلومینیومی", "3": "لعابی", "4": "ملامین", "5": "استیل", "6": "پلاستیکی", "7": "شیشه‌ای", "8": "آرکوپال", "9": "سایر"}	\N	\N	t	56	\N
229	9	U37	EatingDishtwareID2	در چه ظروفی غذا می‌خورید؟ (نوع دوم)	Categorical	{"1": "چینی", "2": "آلومینیومی", "3": "لعابی", "4": "ملامین", "5": "استیل", "6": "پلاستیکی", "7": "شیشه‌ای", "8": "آرکوپال", "9": "سایر"}	\N	\N	f	57	\N
230	9	U38	EatingDishtwareID3	در چه ظروفی غذا می‌خورید؟ (نوع سوم)	Categorical	{"1": "چینی", "2": "آلومینیومی", "3": "لعابی", "4": "ملامین", "5": "استیل", "6": "پلاستیکی", "7": "شیشه‌ای", "8": "آرکوپال", "9": "سایر"}	\N	\N	f	58	\N
231	9	U39	LeftoverContainerTypeID1	غذاهای مانده را در چه ظروفی نگهداری می‌کنید؟ (نوع اول)	Categorical	{"1": "مسی", "2": "چینی", "3": "آلومینیومی", "4": "لعابی", "5": "استیل", "6": "پلاستیکی", "7": "شیشه‌ای", "8": "سایر"}	\N	\N	t	59	\N
232	9	U40	LeftoverContainerTypeID2	غذاهای مانده را در چه ظروفی نگهداری می‌کنید؟ (نوع دوم)	Categorical	{"1": "مسی", "2": "چینی", "3": "آلومینیومی", "4": "لعابی", "5": "استیل", "6": "پلاستیکی", "7": "شیشه‌ای", "8": "سایر"}	\N	\N	f	60	\N
233	9	U14	VegKeepDried	آیا سبزیجات را به صورت خشک شده نگهداری می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	61	\N
234	9	U15	VegKeepRefrigerator	آیا سبزیجات را در یخچال نگهداری می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	62	\N
235	9	U16	VegKeepFreezer	آیا سبزیجات را در فریزر نگهداری می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	63	\N
236	9	U17	VegKeepFresh	آیا سبزیجات را به صورت تازه (بدون نگهداری) استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	64	\N
237	9	U18	FreezVegTypeID	در صورت نگهداری سبزیجات در یخچال یا فریزر، آنها را به چه صورتی نگه می‌دارید؟	Categorical	{"1": "خام", "2": "آب پز شده", "3": "سرخ شده"}	\N	\N	f	65	\N
238	9	U19	FreezMeatTypeID	مواد گوشتی را در یخچال یا فریزر به چه صورتی نگه می‌دارید؟	Categorical	{"1": "خام", "2": "آب پز شده", "3": "سرخ شده", "4": "نگهداری نمی‌کنم (فقط تازه استفاده می‌کنم)"}	\N	\N	t	66	\N
239	9	U41	SpicyFoodIntID	چند وقت یکبار غذاهای تند مصرف می‌کنید؟ (فلفل قرمز یا سیاه)	Categorical	{"0": "هرگز", "1": "کمتر از ۱ بار در ماه", "2": "۱-۳ بار در هفته", "3": "روزانه"}	\N	\N	t	67	\N
240	9	U44	UsedHerbal	نوع گیاه دارویی مورد استفاده:	Characteristic	\N	\N	\N	f	69	\N
241	9	U45	WhyUseHerbal	دلیل استفاده از گیاه دارویی:	Characteristic	\N	\N	\N	f	70	\N
242	13	R7	SmokeInChildhood	آیا در دوران کودکی فردی در خانواده شما سیگار می‌کشید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	f	0	\N
243	7	O19	HasBreastScreening	آیا سابقه غربالگری سرطان پستان یا دهانه رحم داشته‌اید؟	Categorical	{"0": "خیر", "1": "بله", "2": "نمی‌دانم"}	\N	\N	f	21	\N
244	7	O20	LastMammogramAge	سن در زمان آخرین ماموگرافی:	Discrete	\N	سال	\N	f	22	\N
245	7	O22	HasPapSmear	آیا سابقه پاپ اسمیر داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	f	24	\N
246	7	O24	HasMenopause	آیا یائسه شده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	f	26	\N
247	7	O25	MenopauseAge	سن یائسگی:	Discrete	\N	سال	\N	f	27	\N
248	7	O26	NaturalMenopause	آیا یائسگی طبیعی بوده است؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	f	28	\N
249	7	Ob1	HormoneFromAge	سن شروع مصرف داروهای جایگزین هورمونی:	Discrete	\N	سال	\N	f	29	\N
250	7	Ob3	HormoneName	نوع داروی هورمونی:	Characteristic	\N	\N	\N	f	31	\N
251	7	K109	HasPregnancyHypertension	آیا در دوران بارداری به فشار خون بالا (پره اکلامپسی/اکلامپسی) مبتلا شده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	f	17	\N
252	7	K112	HasPregnancyDiabetes	آیا در دوران بارداری به دیابت بارداری مبتلا شده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	f	19	\N
253	8	P1	HasHairLoss	آیا ریزش مو دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	6	\N
254	8	P3	FacialHirsutism	آیا رویش موهای زائد صورت دارید؟ (فقط برای زنان)	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	f	7	\N
255	8	P4	IrisColorID	رنگ عنبیه چشم:	Categorical	{"1": "قهوه‌ای", "2": "فندقی", "3": "سبز", "4": "آبی یا خاکستری"}	\N	\N	t	8	\N
256	8	P5	HasAmputationOrDisability	آیا هرگونه نقص عضو یا ناتوانی دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	9	\N
257	8	P6	HasSpineDisorder	آیا اختلال ستون فقرات دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	10	\N
258	8	P7	SpineDisorderTypeID	نوع اختلال ستون فقرات:	Categorical	{"1": "اسکولیوز", "2": "لوردوز", "3": "کیفوز"}	\N	\N	f	11	\N
259	4	L1	HasSternumIrritation	آیا تاکنون احساس سوزش، درد، فشار یا ناراحتی در قفسه سینه هنگام راه رفتن سریع یا سربالایی داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	40	\N
260	4	L2	HasSwelling	آیا تاکنون ورم یا ادم در هر قسمت از بدن (مخصوصاً پاها) داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	41	\N
261	4	L3	HasUrineColorChanges	آیا تاکنون تغییر رنگ ادرار داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	42	\N
262	4	L4	HasUrinaryProblems	آیا تاکنون مشکلات ادراری (سوزش، تکرر ادرار، شب ادراری، بی اختیاری) داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	43	\N
263	4	L18	HasCough	آیا در یک سال گذشته حداقل به مدت ۲ هفته سرفه داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	44	\N
264	4	L20	HasWheezing	آیا در یک سال گذشته حداقل به مدت ۲ هفته تنگی نفس به همراه خس خس سینه داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	45	\N
265	4	L23	HasHeadTrauma	آیا تاکنون ضربه به سر داشته‌اید که برای مدتی (هرچند کم) بیهوش شوید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	46	\N
266	4	L24	HasRecurrentHeadaches	آیا تاکنون حملات تکرار شونده سردرد داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	47	\N
267	4	L25	HasVertigo	آیا تاکنون حملات سرگیجه داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	48	\N
268	4	L26	HasTinnitus	آیا تاکنون وزوز گوش داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	49	\N
269	4	L27	HasFallHistory	در طول سال گذشته چند بار زمین خورده‌اید؟	Discrete	\N	بار	\N	t	50	\N
270	4	L51	HasSurgery	آیا سابقه جراحی داشته‌اید؟	Categorical	{"1": "بله", "2": "خیر", "3": "نمی‌دانم"}	\N	\N	t	51	\N
272	2	F1	HasJob_new	آیا در حال حاضر شاغل هستید؟	Categorical	{"0": "خیر", "1": "بله", "2": "بازنشسته", "3": "خانه‌دار"}	\N	\N	t	18	\N
273	2	F2	IncomeSourceInsurance	منبع اصلی درآمد: بیمه	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	f	19	\N
274	2	F3	IncomeSourceSelf	منبع اصلی درآمد: خود فرد	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	f	20	\N
275	2	F4	IncomeSourceSpouse	منبع اصلی درآمد: همسر	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	f	21	\N
276	2	F5	IncomeSourceChildren	منبع اصلی درآمد: فرزند یا فرزندان	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	f	22	\N
277	2	F6	IncomeSourceWelfareCharity	منبع اصلی درآمد: کمیته امداد / بهزیستی	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	f	23	\N
278	2	F7	IncomeSourceParents	منبع اصلی درآمد: پدر و مادر	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	f	24	\N
279	2	F8	IncomeSourceOther	منبع اصلی درآمد: سایر	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	f	25	\N
280	2	F9	JobName	نوع شغل خود را نام ببرید:	Characteristic	\N	\N	\N	f	26	\N
281	2	D6	HouseTypeID	نوع خانه:	Categorical	{"1": "آجر و آهن", "2": "چوب و آجر", "3": "بتن/سیمان", "4": "گچ و سنگ", "5": "خشت و گل", "6": "سایر"}	\N	\N	t	28	\N
282	2	D7	CookingFuelTypeID	نوع سوخت پخت و پز:	Categorical	{"1": "نفت/گازوئیل", "2": "چوب و هیمه", "3": "فضولات حیوانی", "4": "گاز", "5": "سایر", "6": "سوختی برای پخت و پز استفاده نمی‌شود"}	\N	\N	t	29	\N
283	2	D8	HeatingFuelTypeID	نوع سوخت گرمایش:	Categorical	{"1": "نفت/گازوئیل", "2": "چوب و هیمه", "3": "فضولات حیوانی", "4": "گاز", "5": "سایر", "6": "سوختی برای گرمایش استفاده نمی‌شود"}	\N	\N	t	30	\N
284	2	D9	HeatingSystemID	سیستم گرمایش:	Categorical	{"1": "بخاری برقی", "2": "بخاری دارای دودکش", "3": "شومینه", "4": "بخاری بدون دودکش/بخاری نفتی", "5": "بخاری گازی", "6": "سایر", "7": "سیستم گرمایشی وجود ندارد"}	\N	\N	t	31	\N
63	5	M3	MedicationIntervalUsedTypeID	دفعات مصرف:	Categorical	{"1": "روزانه", "2": "هفتگی", "3": "ماهانه"}	\N		f	3	medicine
92	5	M1	MedicationID	نام دارو:	Characteristic	\N	\N		f	1	medicine
\.


--
-- TOC entry 5092 (class 0 OID 20994)
-- Dependencies: 231
-- Data for Name: responses; Type: TABLE DATA; Schema: public; Owner: cohort_user
--

COPY public.responses (response_id, submission_id, question_id, v_code, is_voice, transcript, extracted_value, extracted_value_json, ai_confidence, processed_at, group_index) FROM stdin;
\.


--
-- TOC entry 5086 (class 0 OID 20960)
-- Dependencies: 225
-- Data for Name: sections; Type: TABLE DATA; Schema: public; Owner: cohort_user
--

COPY public.sections (section_id, form_id, section_key, name_fa, sort_order, depends_on_vcode, depends_on_value, skip_if_vcode, skip_if_value) FROM stdin;
1	1	identity	مشخصات فردی	1	\N	\N	\N	\N
2	1	socioeconomic	وضعیت اجتماعی اقتصادی	2	\N	\N	\N	\N
3	1	lifestyle	سبک زندگی (آب و تغذیه)	3	\N	\N	\N	\N
4	3	medical_history	سابقه بیماری‌های مزمن	4	\N	\N	\N	\N
5	3	medications	داروهای مصرفی	5	\N	\N	\N	\N
6	3	family_history	سابقه بیماری خانوادگی	6	\N	\N	\N	\N
7	3	reproductive	تاریخچه باروری (زنان)	7	A4	2	\N	\N
8	1	anthropometry	تن‌سنجی (قد و وزن)	8	\N	\N	\N	\N
9	2	nutrition_ffq	بسامد مصرف خوراک (FFQ)	9	\N	\N	\N	\N
10	1	physical_activity	فعالیت فیزیکی	10	\N	\N	\N	\N
11	2	sleep_habits	الگوی خواب	11	\N	\N	\N	\N
12	1	oral_health	بهداشت دهان و دندان	12	\N	\N	\N	\N
13	2	smoking	مصرف دخانیات	13	\N	\N	\N	\N
14	2	alcohol_drugs	الکل و مواد مخدر	14	\N	\N	\N	\N
15	3	blood_pressure	اندازه‌گیری فشار خون	15	\N	\N	\N	\N
16	3	biological_samples	نمونه‌های بیولوژیک	16	\N	\N	\N	\N
\.


--
-- TOC entry 5090 (class 0 OID 20984)
-- Dependencies: 229
-- Data for Name: submissions; Type: TABLE DATA; Schema: public; Owner: cohort_user
--

COPY public.submissions (submission_id, user_id, form_id, status, created_at, updated_at) FROM stdin;
1	3	1	draft	2026-07-08 17:09:40.733792+03:30	2026-07-08 17:14:23.198416+03:30
2	1	1	draft	2026-07-03 21:25:46.105096+03:30	2026-07-12 19:18:23.272174+03:30
3	1	3	draft	2026-08-21 17:23:46.924964+03:30	2026-08-21 17:23:46.924964+03:30
4	3	3	draft	2026-08-21 17:33:32.808064+03:30	2026-08-21 17:33:32.808064+03:30
5	1	2	draft	2026-08-21 18:01:09.451172+03:30	2026-08-21 21:08:11.818572+03:30
6	4	2	draft	2026-08-22 01:03:26.242999+03:30	2026-08-22 01:03:26.242999+03:30
\.


--
-- TOC entry 5082 (class 0 OID 20945)
-- Dependencies: 221
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: cohort_user
--

COPY public.users (user_id, first_name, last_name, national_code, phone_number, role, created_at) FROM stdin;
1	امین	اسماعیلی	0123456789	09123456789	2	2026-05-24 21:00:33.379093+03:30
2	سبحان	عسکری	0123456780	09123456780	2	2026-05-24 21:01:32.8513+03:30
3	علی	علیزاده	0123456781	09991234567	1	2026-07-05 19:35:43.522703+03:30
4	رضا	رضازاده	0954456325	09654783158	1	2026-08-22 01:03:21.30793+03:30
\.


--
-- TOC entry 5101 (class 0 OID 0)
-- Dependencies: 232
-- Name: api_logs_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cohort_user
--

SELECT pg_catalog.setval('public.api_logs_log_id_seq', 1, true);


--
-- TOC entry 5102 (class 0 OID 0)
-- Dependencies: 222
-- Name: forms_form_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cohort_user
--

SELECT pg_catalog.setval('public.forms_form_id_seq', 3, true);


--
-- TOC entry 5103 (class 0 OID 0)
-- Dependencies: 226
-- Name: questions_question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cohort_user
--

SELECT pg_catalog.setval('public.questions_question_id_seq', 284, true);


--
-- TOC entry 5104 (class 0 OID 0)
-- Dependencies: 230
-- Name: responses_response_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cohort_user
--

SELECT pg_catalog.setval('public.responses_response_id_seq', 33, true);


--
-- TOC entry 5105 (class 0 OID 0)
-- Dependencies: 224
-- Name: sections_section_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cohort_user
--

SELECT pg_catalog.setval('public.sections_section_id_seq', 16, true);


--
-- TOC entry 5106 (class 0 OID 0)
-- Dependencies: 228
-- Name: submissions_submission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cohort_user
--

SELECT pg_catalog.setval('public.submissions_submission_id_seq', 6, true);


--
-- TOC entry 5107 (class 0 OID 0)
-- Dependencies: 220
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cohort_user
--

SELECT pg_catalog.setval('public.users_user_id_seq', 4, true);


--
-- TOC entry 4926 (class 2606 OID 21024)
-- Name: api_logs api_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.api_logs
    ADD CONSTRAINT api_logs_pkey PRIMARY KEY (log_id);


--
-- TOC entry 4914 (class 2606 OID 21014)
-- Name: forms forms_pkey; Type: CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.forms
    ADD CONSTRAINT forms_pkey PRIMARY KEY (form_id);


--
-- TOC entry 4918 (class 2606 OID 21018)
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (question_id);


--
-- TOC entry 4920 (class 2606 OID 21061)
-- Name: questions questions_v_code_key; Type: CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_v_code_key UNIQUE (v_code);


--
-- TOC entry 4924 (class 2606 OID 21022)
-- Name: responses responses_pkey; Type: CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.responses
    ADD CONSTRAINT responses_pkey PRIMARY KEY (response_id);


--
-- TOC entry 4916 (class 2606 OID 21016)
-- Name: sections sections_pkey; Type: CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_pkey PRIMARY KEY (section_id);


--
-- TOC entry 4922 (class 2606 OID 21020)
-- Name: submissions submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_pkey PRIMARY KEY (submission_id);


--
-- TOC entry 4910 (class 2606 OID 21063)
-- Name: users users_national_code_key; Type: CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_national_code_key UNIQUE (national_code);


--
-- TOC entry 4912 (class 2606 OID 21012)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4933 (class 2606 OID 21025)
-- Name: api_logs api_logs_submission_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.api_logs
    ADD CONSTRAINT api_logs_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id) ON DELETE CASCADE;


--
-- TOC entry 4928 (class 2606 OID 21030)
-- Name: questions questions_section_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.sections(section_id) ON DELETE CASCADE;


--
-- TOC entry 4931 (class 2606 OID 21035)
-- Name: responses responses_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.responses
    ADD CONSTRAINT responses_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(question_id) ON DELETE CASCADE;


--
-- TOC entry 4932 (class 2606 OID 21040)
-- Name: responses responses_submission_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.responses
    ADD CONSTRAINT responses_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id) ON DELETE CASCADE;


--
-- TOC entry 4927 (class 2606 OID 21045)
-- Name: sections sections_form_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(form_id) ON DELETE CASCADE;


--
-- TOC entry 4929 (class 2606 OID 21050)
-- Name: submissions submissions_form_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(form_id) ON DELETE CASCADE;


--
-- TOC entry 4930 (class 2606 OID 21055)
-- Name: submissions submissions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cohort_user
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


-- Completed on 2026-08-22 17:22:52

--
-- PostgreSQL database dump complete
--

\unrestrict j47voibEIHWbdcPzwvSEtwxmIWAuifofocBUJqqfNBS7NNnukA4XcZmhggdtip8

