--
-- PostgreSQL database dump
--

\restrict n4U4PqBuA3DpvosVc0Piq8sbbN1iByze3DmfaenbK2McCSMqvU3YflIgsr86O1G

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-09-02 13:10:06

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 17360)
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- TOC entry 5013 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 17371)
-- Name: api_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_logs (
    log_id integer NOT NULL,
    submission_id integer,
    section_key character varying(50),
    model_name character varying(100),
    prompt_sent text,
    response_received text,
    tokens_used integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.api_logs OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17378)
-- Name: api_logs_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_logs ALTER COLUMN log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_logs_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 17379)
-- Name: forms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forms (
    form_id integer NOT NULL,
    form_name character varying(255) NOT NULL,
    category character varying(100),
    is_active boolean DEFAULT true,
    sort_order integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.forms OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17387)
-- Name: forms_form_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forms ALTER COLUMN form_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 17388)
-- Name: health_checks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.health_checks (
    check_id integer NOT NULL,
    user_id integer NOT NULL,
    summary text NOT NULL,
    full_report text NOT NULL,
    full_report_html text,
    model_name character varying(100),
    prompt_sent text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.health_checks OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17398)
-- Name: health_checks_check_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.health_checks_check_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.health_checks_check_id_seq OWNER TO postgres;

--
-- TOC entry 5014 (class 0 OID 0)
-- Dependencies: 225
-- Name: health_checks_check_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.health_checks_check_id_seq OWNED BY public.health_checks.check_id;


--
-- TOC entry 226 (class 1259 OID 17399)
-- Name: questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questions (
    question_id integer NOT NULL,
    section_id integer NOT NULL,
    v_code character varying(20) NOT NULL,
    variable_name character varying(100),
    question_text_fa text NOT NULL,
    response_type character varying(50) NOT NULL,
    coding_options jsonb,
    unit character varying(50),
    manual_prompt text,
    is_required boolean DEFAULT true,
    sort_order integer DEFAULT 0,
    group_pair character varying(100),
    visibility_rules jsonb
);


ALTER TABLE public.questions OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17411)
-- Name: questions_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.questions ALTER COLUMN question_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questions_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17412)
-- Name: responses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.responses (
    response_id integer NOT NULL,
    submission_id integer,
    question_id integer NOT NULL,
    v_code character varying(20),
    is_voice boolean DEFAULT true,
    transcript text,
    extracted_value text,
    extracted_value_json jsonb,
    ai_confidence double precision,
    processed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    group_index integer
);


ALTER TABLE public.responses OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17421)
-- Name: responses_response_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.responses ALTER COLUMN response_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.responses_response_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 17422)
-- Name: sections; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sections (
    section_id integer NOT NULL,
    form_id integer NOT NULL,
    section_key character varying(50) NOT NULL,
    name_fa character varying(255) NOT NULL,
    sort_order integer DEFAULT 0,
    depends_on_vcode character varying(20),
    depends_on_value text,
    skip_if_vcode character varying(20),
    skip_if_value text
);


ALTER TABLE public.sections OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17432)
-- Name: sections_section_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sections ALTER COLUMN section_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sections_section_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 17433)
-- Name: submissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.submissions (
    submission_id integer NOT NULL,
    user_id integer NOT NULL,
    form_id integer NOT NULL,
    status character varying(20) DEFAULT 'draft'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.submissions OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17442)
-- Name: submissions_submission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.submissions ALTER COLUMN submission_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submissions_submission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 17443)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    first_name character varying(100),
    last_name character varying(100),
    national_code character varying(20) NOT NULL,
    phone_number character varying(20),
    role integer DEFAULT 1,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    email character varying(255),
    sex character varying(10),
    birth_date date
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 17452)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4804 (class 2604 OID 17453)
-- Name: health_checks check_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.health_checks ALTER COLUMN check_id SET DEFAULT nextval('public.health_checks_check_id_seq'::regclass);


--
-- TOC entry 4992 (class 0 OID 17371)
-- Dependencies: 220
-- Data for Name: api_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_logs (log_id, submission_id, section_key, model_name, prompt_sent, response_received, tokens_used, created_at) FROM stdin;
\.


--
-- TOC entry 4994 (class 0 OID 17379)
-- Dependencies: 222
-- Data for Name: forms; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.forms (form_id, form_name, category, is_active, sort_order) FROM stdin;
1	پرسشنامه عمومی	general	t	1
2	پرسشنامه تغذیه	nutrition	t	3
3	پرسشنامه پزشکی	medical	t	2
\.


--
-- TOC entry 4996 (class 0 OID 17388)
-- Dependencies: 224
-- Data for Name: health_checks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.health_checks (check_id, user_id, summary, full_report, full_report_html, model_name, prompt_sent, created_at) FROM stdin;
\.


--
-- TOC entry 4998 (class 0 OID 17399)
-- Dependencies: 226
-- Data for Name: questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.questions (question_id, section_id, v_code, variable_name, question_text_fa, response_type, coding_options, unit, manual_prompt, is_required, sort_order, group_pair, visibility_rules) FROM stdin;
168	1	A8	MotherEthnicityID	قومیت مادر:	Categorical	{"1": "فارس", "2": "آذری", "3": "بلوچ", "4": "کرد", "5": "لر", "6": "عرب", "7": "ترکمن", "8": "تالش", "9": "زابلی", "10": "گیلک", "11": "ترک ایل", "12": "عرب ایل", "13": "مازنی", "14": "توت", "15": "سایر", "16": "ترک"}	\N		t	5	\N	[null]
201	9	V2	Water_SummerInterval	بازه زمانی مصرف آب در تابستان:	Categorical	{"1": "در روز", "2": "در هفته", "3": "در ماه"}	\N	\N	t	24	\N	{"logic": "all", "rules": [{"v_code": "U2", "values": ["2"]}]}
194	9	U3	FoodSaltUsedID	غذایی که می‌خورید چقدر شور است؟	Categorical	{"1": "کم نمک", "2": "معمولی", "3": "شور"}	\N		t	13	\N	[null]
4	1	A5	Age	سن:	Discrete	\N	\N		t	4	\N	\N
2	1	A3	CohortCenterID	مرکز کوهورت:	Categorical	{"2": "روانسر", "3": "گیلان", "4": "فسا", "5": "آذر", "6": "خرامه", "7": "مازندران", "8": "زاهدان", "9": "یزد", "10": "رفسنجان", "11": "هویزه", "12": "شهرکرد", "13": "بندرکنگ", "14": "دریاچه ارومیه", "15": "اردبیل", "16": "سبزوار", "17": "مشهد", "18": "دنا", "19": "کوار", "20": "دهقلان"}	\N		t	2	\N	\N
69	5	Ma2	Anti_DM_Pills	آیا از داروهای خوراکی دیابت استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	5	\N	\N
70	5	Ma3	Insulin	آیا از انسولین استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	6	\N	\N
71	5	Ma4	Statins	آیا از استاتین‌ها استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	7	\N	\N
74	7	O1	HasMenstruation	آیا تاکنون قاعده شده‌اید؟	Categorical	{"0": "خیر", "1": "بله"}	\N		t	1	\N	\N
112	12	Q4	MissingTeethNo	تعداد دندان‌های کشیده شده:	Discrete	\N	دندان		t	5	\N	\N
185	9	T28	Milk	شیر:	Continuous	\N	گرم در روز		t	6	\N	[null]
176	2	C23	BookNoRead	تعداد کتاب‌های غیر درسی که در یک سال گذشته مطالعه کرده‌اید:	Discrete	\N	کتاب		t	13	\N	\N
258	8	P7	SpineDisorderTypeID	نوع اختلال ستون فقرات:	Categorical	{"1": "اسکولیوز", "2": "لوردوز", "3": "کیفوز"}	\N	\N	t	11	\N	{"logic": "all", "rules": [{"v_code": "P6", "values": ["1"]}]}
255	8	P4	IrisColorID	رنگ عنبیه چشم:	Categorical	{"1": "مشکی", "2": "قهوه‌ای", "3": "سبز", "4": "آبی یا خاکستری", "5": "سایر"}	\N	\N	t	8	\N	\N
240	9	U44	UsedHerbal	نوع گیاه دارویی مورد استفاده:	Characteristic	\N	\N	\N	t	69	herbal	\N
270	4	L51	HasSurgery	آیا سابقه جراحی داشته‌اید؟	Categorical	{"0": "خیر", "1": "بله", "2": "نمی‌دانم"}	\N	\N	t	51	\N	\N
242	13	R8	SmokeInChildhood	آیا در دوران کودکی فردی در خانواده شما سیگار می‌کشید؟	Dichotomous	{"0": "خیر", "1": "بله"}			t	1	\N	\N
272	2	F1	HasJob_new	آیا در حال حاضر شاغل هستید؟	Categorical	{"0": "خیر", "1": "بله", "2": "بازنشسته", "3": "خانه‌دار"}	\N	\N	t	18	\N	\N
281	2	D6	HouseTypeID	نوع خانه:	Categorical	{"1": "آجر و آهن", "2": "چوب و آجر", "3": "بتن/سیمان", "4": "گچ و سنگ", "5": "خشت و گل", "6": "سایر"}	\N	\N	t	28	\N	\N
282	2	D7	CookingFuelTypeID	نوع سوخت پخت و پز:	Categorical	{"1": "نفت/گازوئیل", "2": "چوب و هیمه", "3": "فضولات حیوانی", "4": "گاز", "5": "سایر", "6": "سوختی برای پخت و پز استفاده نمی‌شود"}	\N	\N	t	29	\N	\N
283	2	D8	HeatingFuelTypeID	نوع سوخت گرمایش:	Categorical	{"1": "نفت/گازوئیل", "2": "چوب و هیمه", "3": "فضولات حیوانی", "4": "گاز", "5": "سایر", "6": "سوختی برای گرمایش استفاده نمی‌شود"}	\N	\N	t	30	\N	\N
36	3	I2	MobileUseDuration	چند سال است که از تلفن همراه استفاده می‌کنید؟	Continuous	\N	سال		t	15	\N	{"logic": "all", "rules": [{"v_code": "I1", "values": ["1"]}]}
271	4	L52	SurgeryNo	تعداد دفعات جراحی:	Discrete	\N	بار	\N	t	52	\N	{"logic": "all", "rules": [{"v_code": "L51", "values": ["1"]}]}
39	3	J3	UseInFarm	آیا از سموم آفت‌کش در مزرعه، گلخانه یا زمین‌های کشاورزی استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	18	\N	\N
40	3	J35	ManageSprayingPesticide	آیا مدیریت عملیات اسپری کردن سموم را بر عهده دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	20	\N	\N
289	5	M4	Meds	آیا از دارویی/قرصی استفاده میکنید؟	Categorical	{"0": "خیر", "1": "بله"}	\N	\N	t	1	\N	\N
92	5	M1	MedicationID	نام دارو:	Characteristic	\N	\N		t	2	medicine	{"logic": "all", "rules": [{"v_code": "M4", "values": ["1"]}]}
63	5	M3	MedicationIntervalUsedTypeID	دفعات مصرف:	Categorical	{"1": "روزانه", "2": "هفتگی", "3": "ماهانه"}	\N		t	3	medicine	{"logic": "all", "rules": [{"v_code": "M4", "values": ["1"]}]}
66	5	Ma1	Anti_HTN_Drug	آیا از داروهای فشار خون استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	4	\N	{"logic": "all", "rules": [{"v_code": "M4", "values": ["1"]}]}
75	7	O2	MenstruationStartAge	سن شروع قاعدگی:	Discrete	\N	سال		t	2	\N	\N
76	7	O3	NowPregnant	آیا در حال حاضر باردار هستید؟	Categorical	{"1": "بله", "2": "خیر", "3": "نمی‌داند"}	\N		t	3	\N	\N
8	1	A30	ResidenceType	نوع محل سکونت:	Categorical	{"1": "شهری", "2": "روستایی"}	\N		t	14	\N	\N
9	2	C1	HousingStatusID	وضعیت تملک مسکن:	Categorical	{"1": "ملک شخصی", "2": "ملک رهنی یا استیجاری", "3": "ملک سازمانی", "4": "ملک خویشاوندان (امانتی)"}	\N		t	1	\N	\N
10	2	C4	FamilyNo	تعداد افرادی که با هم در منزل زندگی می‌کنید:	Discrete	\N	نفر		t	4	\N	\N
19	2	C24	ForeignTravelNo	تعداد مسافرت‌های خارج از ایران (کل عمر):	Discrete	\N	مورد		t	14	\N	\N
20	2	C25	ForeignPilgrimageNo	تعداد مسافرت‌های زیارتی خارج از ایران:	Discrete	\N	مورد		t	15	\N	\N
21	2	C26	ForeignNonPilgrimageNo	تعداد مسافرت‌های غیر زیارتی خارج از ایران:	Discrete	\N	مورد		t	16	\N	\N
22	3	E1	WaterSourceID1	منبع اصلی آب آشامیدنی شما چیست؟ (منبع اول)	Categorical	{"1": "آب چاه", "2": "آب رودخانه", "3": "آب چشمه", "4": "آب لوله کشی", "5": "آب معدنی", "6": "تانکر آب", "7": "آب انبار", "8": "سایر"}	\N		t	1	\N	\N
24	3	H3	FallingSleepDurationMin	از زمانی که به رختخواب می‌روید تا خوابتان ببرد چقدر طول می‌کشد؟	Discrete	\N	دقیقه		t	6	\N	\N
25	3	H4	MorningWakeupHour	معمولاً صبح‌ها چه ساعتی بیدار می‌شوید؟ (ساعت)	Discrete	\N	ساعت		t	7	\N	\N
26	3	H5	MorningWakeupMin	معمولاً صبح‌ها چه ساعتی بیدار می‌شوید؟ (دقیقه)	Discrete	\N	دقیقه		t	8	\N	\N
27	3	H8	DayTimeNap	آیا در طول روز می‌خوابید؟ (سه بار یا بیشتر در هفته)	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	9	\N	\N
30	3	H13	DozingOff	آیا در طول روز وقتی فعالیتی ندارید بدون اختیار چرت می‌زنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	12	\N	\N
31	3	H14	SleepingPillsUse	آیا از داروهای خواب آور بطور مداوم استفاده می‌کنید؟ (بیشتر از ۲ بار در هفته)	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	13	\N	\N
32	3	I1	MobileUse	آیا تلفن همراه دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	14	\N	\N
34	3	H1	NightSleepHour	معمولاً شب‌ها چه ساعتی می‌خوابید؟ (ساعت)	Discrete	\N	ساعت		t	4	\N	\N
35	3	H2	NightSleepMin	معمولاً شب‌ها چه ساعتی می‌خوابید؟ (دقیقه)	Discrete	\N	دقیقه		t	5	\N	\N
37	3	J1	NearFarm	آیا منزل شما نزدیک مناطقی که در آن کشت و کار انجام می‌شود قرار دارد؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	16	\N	\N
5	1	A26	MarriageNo	تعداد ازدواج:	Discrete	\N	بار		t	11	\N	{"logic": "all", "rules": [{"v_code": "A24", "values": ["2", "3", "4"]}]}
33	3	E4	TapWaterUseYear	چند سال است که از آب لوله کشی استفاده می‌کنید؟	Continuous	\N	سال		t	3	\N	{"logic": "all", "rules": [{"v_code": "E1", "values": ["4"]}]}
23	3	E3	TapWaterAllTime	آیا همیشه از آب لوله کشی استفاده کرده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	2	\N	{"logic": "all", "rules": [{"v_code": "E1", "values": ["4"]}]}
28	3	H9	NapDurationMin	هر بار چند دقیقه می‌خوابید؟	Discrete	\N	دقیقه		t	10	\N	{"logic": "all", "rules": [{"v_code": "H8", "values": ["1"]}]}
77	7	O4	PregnancyNo	تعداد حاملگی‌های قبلی:	Discrete	\N	مورد		t	4	\N	\N
78	7	O5	FirstPregnancyAge	سن در زمان اولین حاملگی:	Discrete	\N	سال		t	5	\N	\N
79	7	O6	AliveChildbirthNo	تعداد زایمان‌های با نوزاد زنده:	Discrete	\N	مورد		t	6	\N	\N
80	7	O7	FirstAliveChildbirthAge	سن در زمان اولین تولد نوزاد زنده:	Discrete	\N	سال		t	7	\N	\N
38	3	J2	FarmDistanceID	فاصله مزرعه تا منزل:	Categorical	{"1": "دور (بیشتر از ۲۰۰ متر)", "2": "تقریباً نزدیک (۱۰۰-۲۰۰ متر)", "3": "نزدیک (۵۰-۱۰۰ متر)", "4": "خیلی نزدیک (کمتر از ۵۰ متر)"}	\N		t	17	\N	{"logic": "all", "rules": [{"v_code": "J1", "values": ["1"]}]}
81	7	O8	HasStillbirth	آیا سابقه مرده‌زایی دارید؟	Categorical	{"0": "خیر", "1": "بله"}	\N		t	8	\N	\N
82	7	O9	AbortionNo	تعداد سقط:	Discrete	\N	مورد		t	9	\N	\N
83	7	O10	FirstAbortionAge	سن در زمان اولین سقط:	Discrete	\N	سال		t	10	\N	\N
84	7	O11	BreastfeedingDuration	مجموع مدت شیردهی:	Continuous	\N	ماه		t	11	\N	\N
85	7	O12	HasInfertility	آیا سابقه نازایی دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	12	\N	\N
86	7	O14	OvaryRemovalTypeID	آیا سابقه برداشتن تخمدان دارید؟	Categorical	{"1": "بله، یک طرفه", "2": "بله، دو طرفه", "3": "خیر"}	\N		t	13	\N	\N
87	7	O16	HasTubectomy	آیا سابقه توبکتومی دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	14	\N	\N
88	7	O17	HasHysterectomy	آیا سابقه هیسترکتومی دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	15	\N	\N
89	7	Oa3	ContraceptionTypeID	روش پیشگیری از بارداری:	Categorical	{"1": "قرص‌های پیشگیری", "2": "ایمپلنت", "3": "تزریق پروژسترون طولانی مدت", "4": "وسایل داخل رحمی (IUD)"}	\N		t	16	\N	\N
90	8	B3	WaistCircumference	دور کمر:	Continuous	\N	سانتی متر		t	3	\N	\N
91	8	B4	HipCircumference	دور باسن:	Continuous	\N	سانتی متر		t	4	\N	\N
93	10	G18	AerobicExercise1	پیاده‌روی سریع، ورزش آئروبیک سبک:	Continuous	\N	ساعت		t	9	\N	\N
94	10	G21	HeavyLaborAgricultJobs1	فعالیت‌های سنگین کارگری/کشاورزی:	Continuous	\N	ساعت		t	10	\N	\N
95	10	G22	HeavyExercise1	فعالیت‌های ورزشی حرفه‌ای:	Continuous	\N	ساعت		t	11	\N	\N
96	10	G23	Duration1	تعداد ماه‌هایی که این الگوی فعالیت را دارید:	Discrete	\N	ماه در سال		t	12	\N	\N
97	11	H6	PreferredWakeupHour	دوست دارید صبح‌ها چه ساعتی بیدار شوید؟ (ساعت)	Discrete	\N	ساعت		t	1	\N	\N
98	11	H7	PreferredWakeupMin	دوست دارید صبح‌ها چه ساعتی بیدار شوید؟ (دقیقه)	Discrete	\N	دقیقه		t	2	\N	\N
99	11	H12	LegRestlessnessID	آیا در طول خواب پاهایتان زیاد حرکت می‌کند؟	Categorical	{"1": "بله", "2": "خیر", "3": "نمی‌دانم"}	\N		t	3	\N	\N
101	8	B5	WristCircumference	دور مچ:	Continuous	\N	سانتی متر		t	5	\N	\N
102	10	G1	SleepDuration24h1	خواب شبانه (متوسط):	Continuous	\N	ساعت		t	1	\N	\N
103	10	G2	SleepDurationMidDay1	خواب عصر/میان‌روز:	Continuous	\N	ساعت		t	2	\N	\N
104	10	G4	TV1	تماشای تلویزیون/فیلم/گوش دادن به موسیقی:	Continuous	\N	ساعت		t	3	\N	\N
105	10	G5	Study1	مطالعه کتاب/مجله/روزنامه:	Continuous	\N	ساعت		t	4	\N	\N
106	10	G8	Eating1	غذا خوردن، نشستن در جلسات/مهمانی‌ها:	Continuous	\N	ساعت		t	5	\N	\N
107	10	G11	Cooking1	آشپزی، شستن ظروف، فعالیت‌های ایستاده:	Continuous	\N	ساعت		t	6	\N	\N
108	10	G12	HouseCleaning1	نظافت منزل، شستن لباس، جارو کشیدن:	Continuous	\N	ساعت		t	7	\N	\N
109	10	G14	Walking1	پیاده‌روی آهسته، پایین رفتن از پله:	Continuous	\N	ساعت		t	8	\N	\N
110	12	Q2	TeethNo	تعداد کل دندان‌ها:	Discrete	\N	دندان		t	3	\N	\N
116	12	Q8	FlossingNo	چند بار در هفته از نخ دندان استفاده می‌کنید؟		\N	بار در هفته		t	9	\N	{"logic": "all", "rules": [{"v_code": "Q7", "values": ["1"]}]}
111	12	Q3	DecayedTeethNo	تعداد دندان‌های پوسیده:	Discrete	\N	دندان		t	4	\N	\N
113	12	Q5	FilledTeeth	تعداد دندان‌های پر شده:	Discrete	\N	دندان		t	6	\N	\N
121	13	R3	FirstCigaretteAge	اولین سیگار را در چه سنی کشیدید؟	Text	\N	سالگی		t	5	\N	{"logic": "all", "rules": [{"v_code": "R1", "values": ["1"]}]}
123	13	R5	CurrentSmokingTypeID	آیا هم اکنون سیگار می‌کشید؟	Categorical	{"0": "خیر", "1": "بله، روزانه", "2": "گاهی اوقات"}			t	6	\N	{"logic": "all", "rules": [{"v_code": "R1", "values": ["1"]}]}
122	13	R4	RegularCigaretteAge	سیگار را به طور منظم از چه سنی شروع کردید؟	Text	\N	سالگی		t	7	\N	{"logic": "all", "rules": [{"v_code": "R5", "values": ["1"]}]}
126	13	R10	SmokeInHomeNo	چند ساعت در روز در تماس با دود سیگار در منزل هستید؟	Continuous	\N	ساعت در روز		t	10	\N	{"logic": "all", "rules": [{"v_code": "R9", "values": ["1"]}]}
73	6	N3	FamilyRelationID	نسبت فامیلی با بیمار:	MultiSelect	{"1": "پدر", "2": "مادر", "3": "برادر", "4": "خواهر", "5": "برادر ناتنی", "6": "خواهر ناتنی", "7": "پسر", "8": "دختر", "9": "پدربزرگ/مادربزرگ", "10": "همسر", "11": "سایر خویشاوندان درجه دو"}	\N		t	3	\N	{"logic": "all", "rules": [{"v_code": "N1", "values": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26"]}]}
159	4	L55	DrugAllergy	آیا به داروی خاصی حساسیت دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	39	\N	\N
160	9	U10	ReUseOil	آیا روغن پس از سرخ کردن را دوباره استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	17	\N	\N
161	9	U12	ReUseMold	اگر غذایی مثل رب، مربا، ترشی کپک زده بود، قسمتی از آن را برداشته و بقیه را مصرف می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	18	\N	\N
162	9	U13	SmokedFoodIntID	آیا از غذاهای دودی (برنج دودی، ماهی دودی) استفاده می‌کنید؟	Categorical	{"0": "هرگز", "1": "کمتر از ۱-۳ بار در ماه", "2": "۱-۳ بار در هفته", "3": "روزانه"}	\N		t	19	\N	\N
164	9	U21	SoupTempUseID	سوپ، آش و سایر غذاهای آبکی را با چه دمایی می‌خورید؟	Categorical	{"1": "داغ", "2": "گرم (وارم)", "3": "سرد", "4": "مصرف نمی‌کند"}	\N		t	21	\N	\N
165	9	U43	UseBoiledHerbal	آیا از دمنوش‌های داروهای گیاهی، عرقیجات و یا پودرهای گیاهی استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	22	\N	\N
166	8	B1	HeightCm	قد چند سانتی متر است	Continuous	\N	سانتی متر		t	1	\N	\N
167	8	B2	WeightKg	وزن:	Continuous	\N	کیلوگرم		t	2	\N	\N
130	14	Rc3	DrugTypeID	نوع ماده مخدر؟	MultiSelect	{"1": "تریاک", "2": "هروئین", "3": "سوخته", "4": "شیره", "5": "شیشه", "6": "کوکائین", "7": "کراک", "8": "کریستال", "9": "پان", "10": "سایر"}			t	2	\N	{"logic": "all", "rules": [{"v_code": "R13", "values": ["1"]}]}
133	14	Rc4	DrugUseTypeID	روش مصرف:	MultiSelect	{"1": "خوراکی", "2": "استنشاقی", "3": "تزریقی"}	\N		t	3	\N	{"logic": "all", "rules": [{"v_code": "R13", "values": ["1"]}]}
148	4	L6	HasHeartburn	آیا در یک سال گذشته دچار سوزش سردل شده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	28	\N	\N
149	4	L7	HeartburnFrequencyOfOccurrence	تعداد دفعات سوزش سردل:	Categorical	{"1": "تقریباً هر روز", "2": "چند بار در ماه", "3": "چند بار در هفته", "4": "گاهی"}	\N		t	29	\N	{"logic": "all", "rules": [{"v_code": "L6", "values": ["1"]}]}
132	14	Rd3	AlcoholTypeID	نوع مشروبات الکلی ؟	MultiSelect	{"1": "آبجو", "2": "مشروبات با الکل بالا (۴۰٪ و دکا، ویسکی، جین)", "3": "مشروبات دست ساز", "4": "سایر"}			t	5	\N	{"logic": "all", "rules": [{"v_code": "R14", "values": ["1"]}]}
169	1	A10	FatherEthnicityID	قومیت پدر:	Categorical	{"1": "فارس", "2": "آذری", "3": "بلوچ", "4": "کرد", "5": "لر", "6": "عرب", "7": "ترکمن", "8": "تالش", "9": "زابلی", "10": "گیلک", "11": "ترک ایل", "12": "عرب ایل", "13": "مازنی", "14": "توت", "15": "سایر", "16": "ترک"}	\N		t	6	\N	\N
170	1	A20	EducationYears	تعداد سال‌های تحصیل:	Discrete	\N	سال		t	7	\N	\N
171	1	A21	LastEduID	آخرین مدرک تحصیلی:	Categorical	{"1": "ابتدایی", "2": "راهنمایی", "3": "دیپلم", "4": "فوق دیپلم", "5": "لیسانس", "6": "فوق لیسانس", "7": "دکترا", "8": "بی سواد"}	\N		t	8	\N	\N
172	1	A22	FamilyStatusID	موقعیت شما در خانواده:	Categorical	{"1": "پدر", "2": "مادر", "3": "فرزند", "4": "پدربزرگ/مادربزرگ", "5": "عمه/عمو", "6": "خاله/دایی", "7": "سایر"}	\N		t	9	\N	\N
173	9	U2	SaltUseID	آیا به غذای خود نمک اضافه می‌کنید؟	Categorical	{"1": "بله", "2": "گاهی", "3": "خیر"}	\N		t	12	\N	\N
174	2	C2	HouseArea	متراژ واحد مسکونی:	Continuous	\N	متر مربع		t	2	\N	\N
175	2	C3	HouseroomNo	تعداد اتاق‌های خواب:	Discrete	\N	اتاق		t	3	\N	\N
177	2	C27	NationalTravelNo	تعداد مسافرت‌های داخل ایران در ده سال گذشته:	Discrete	\N	مورد		t	17	\N	\N
178	3	H10	NightShiftWork	آیا در طول یک سال گذشته کار شبانه داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	11	\N	\N
179	3	J11	UseInHome	آیا از حشره‌کش در خانه استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	19	\N	\N
180	9	T1	Bread_Lavash	نان لواش:	Continuous	\N	گرم در روز		t	1	\N	\N
181	9	T5	Cooked_rice	برنج پخته:	Continuous	\N	گرم در روز		t	2	\N	\N
182	9	T15	Red_meat	گوشت قرمز:	Continuous	\N	گرم در روز		t	3	\N	\N
183	9	T16	Chicken	گوشت مرغ:	Continuous	\N	گرم در روز		t	4	\N	\N
184	9	T18	Eggs	تخم مرغ:	Continuous	\N	گرم در روز		t	5	\N	\N
186	9	T29	Yogurt	ماست:	Continuous	\N	گرم در روز		t	7	\N	\N
187	9	T30	Cheese	پنیر:	Continuous	\N	گرم در روز		t	8	\N	\N
188	9	T31	Doogh	دوغ:	Continuous	\N	گرم در روز		t	9	\N	\N
189	9	T113	Salt	نمک:	Continuous	\N	گرم در روز		t	10	\N	\N
193	9	U1	EatIntID	به طور متوسط چند وعده غذا در روز می‌خورید؟	Categorical	{"1": "۳ وعده (صبحانه، ناهار، شام)", "2": "۴ وعده", "3": "۵-۶ وعده", "4": "بیشتر از ۶ وعده", "5": "کمتر از ۳ وعده"}	\N		t	11	\N	\N
163	9	U20	TeaTempUseID	چای و قهوه را با چه دمایی می‌خورید؟	Categorical	{"1": "داغ", "2": "گرم (وارم)", "3": "سرد", "4": "مصرف نمی‌کند"}	\N		t	20	\N	[null]
195	9	U4	GrilledFoodIntID	چند وقت یکبار غذای کبابی مصرف می‌کنید؟	Categorical	{"0": "هرگز", "1": "کمتر از یک بار در ماه", "2": "۱-۳ بار در ماه", "3": "۱-۳ بار در هفته", "4": "روزانه"}	\N		t	14	\N	\N
196	9	U5	FriedFoodIntID	چند وقت یکبار غذای سرخ شده مصرف می‌کنید؟	Categorical	{"0": "هرگز", "1": "کمتر از یک بار در ماه", "2": "۱-۳ بار در ماه", "3": "۱-۳ بار در هفته", "4": "روزانه"}	\N		t	15	\N	\N
197	9	U9	UsedOilTypeID	چه نوع روغنی برای سرخ کردن استفاده می‌کنید؟	Categorical	{"1": "روغن جامد (دنبه/کره)", "2": "روغن نیمه جامد (مارگارین)", "3": "روغن مایع", "4": "روغن مخصوص سرخ کردنی", "5": "سایر", "6": "سرخ کردن انجام نمی‌دهم"}	\N		t	16	\N	\N
200	9	V1	Water_inSummer	میزان آب مصرفی در تابستان:	Discrete	\N	لیوان	(هر لیوان معادل ۲۳۰ میلی‌لیتر)	t	23	\N	\N
202	9	V3	Water_inOther	میزان آب مصرفی در سایر فصل‌ها:	Discrete	\N	لیوان	(هر لیوان معادل ۲۳۰ میلی‌لیتر)	t	25	\N	\N
203	9	V4	Water_OtherInterval	بازه زمانی مصرف آب در سایر فصل‌ها:	Categorical	{"1": "در روز", "2": "در هفته", "3": "در ماه"}	\N	\N	t	26	\N	\N
204	9	W1	SupMultiVitaminMineralInterval	مولتی‌ویتامین و مینرال:	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	t	27	\N	\N
190	1	A27	FirstMarriageAge	سن در زمان اولین ازدواج:	Discrete	\N	سال		t	12	\N	{"logic": "all", "rules": [{"v_code": "A24", "values": ["2", "3", "4"]}]}
199	3	EA4	AnimalTypeID	نوع حیوان:	MultiSelect	{"1": "اسب سانان (اسب، قاطر، الاغ، شتر)", "2": "نشخوارکنندگان (گوسفند، بز، گاو)", "3": "سگ", "4": "طیور", "5": "گربه", "6": "سایر"}	\N	\N	t	22	\N	{"logic": "all", "rules": [{"v_code": "EA3", "values": ["1", "2", "3", "4"]}]}
192	13	R9	SmokeInHome	آیا در معرض تماس با دود سیگار در منزل بوده/هستید؟	Dichotomous	{"0": "خیر", "1": "بله"}			t	9	\N	\N
227	9	U35	UsedScratchedTeflon	آیا از ظروف تفلون که سطوحشان خراش دارد استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	55	\N	\N
218	9	U26	LemonContainerTypeID1	از چه نوع ظروفی برای نگهداری آبلیمو و آبغوره استفاده می‌کنید؟	MultiSelect	{"1": "پلاستیکی", "2": "استیل", "4": "شیشه‌ای", "5": "سایر", "6": "نگهداری نمی‌کنم"}	\N	\N	t	46	\N	\N
220	9	U28	TomatoContainerTypeID1	از چه نوع ظروفی برای نگهداری رب و آب گوجه فرنگی استفاده می‌کنید؟	MultiSelect	{"1": "پلاستیکی", "2": "استیل", "4": "شیشه‌ای", "5": "سایر", "6": "نگهداری نمی‌کنم"}	\N	\N	t	48	\N	\N
222	9	U30	PicklesContainerTypeID1	از چه نوع ظروفی برای نگهداری ترشی و خیارشور استفاده می‌کنید؟	MultiSelect	{"1": "پلاستیکی", "2": "استیل", "4": "شیشه‌ای", "5": "سایر", "6": "نگهداری نمی‌کنم"}	\N	\N	t	50	\N	\N
224	9	U32	CookingWareID1	از چه نوع ظروفی برای پخت و پز استفاده می‌کنید؟	MultiSelect	{"1": "روکش روی", "2": "مسی", "3": "آلومینیومی", "4": "لعابی", "5": "تفلون", "6": "چدنی", "7": "استیل", "8": "پیرکس", "9": "سایر"}	\N	\N	t	52	\N	\N
228	9	U36	EatingDishtwareID1	در چه ظروفی غذا می‌خورید؟	MultiSelect	{"1": "چینی", "2": "آلومینیومی", "3": "لعابی", "4": "ملامین", "5": "استیل", "6": "پلاستیکی", "7": "شیشه‌ای", "8": "آرکوپال", "9": "سایر"}	\N	\N	t	56	\N	\N
231	9	U39	LeftoverContainerTypeID1	غذاهای مانده را در چه ظروفی نگهداری می‌کنید؟	MultiSelect	{"1": "مسی", "2": "چینی", "3": "آلومینیومی", "4": "لعابی", "5": "استیل", "6": "پلاستیکی", "7": "شیشه‌ای", "8": "سایر"}	\N	\N	t	59	\N	\N
207	9	W7	SupCalciumInterval	کلسیم:	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	t	33	\N	\N
208	9	W9	SupVitaminDPillInterval	ویتامین D (قرص):	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	t	35	\N	\N
209	9	W11	SupVitaminDValInterval	ویتامین D (آمپول):	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	t	37	\N	\N
210	9	F11_6	FolicAcid	اسیدفولیک:	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	t	38	\N	\N
211	9	F11_7	Omega3	روغن ماهی / امگا ۳:	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	t	39	\N	\N
212	9	F11_8	Iron	آهن:	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	t	40	\N	\N
213	9	F11_9	Zinc	روی یا زینک:	Categorical	{"0": "هرگز", "1": "روزانه", "2": "هفتگی", "3": "ماهانه", "4": "سالانه"}	\N	\N	t	41	\N	\N
216	9	U24	BreadContainerTypeID1	از چه نوع ظروفی برای نگهداری نان استفاده می‌کنید؟	MultiSelect	{"1": "پلاستیکی", "2": "استیل", "3": "پارچه‌ای", "4": "شیشه‌ای", "5": "سایر", "6": "نگهداری نمی‌کنم"}	\N	\N	t	44	\N	\N
233	9	U14	VegKeepDried	آیا سبزیجات را به صورت خشک شده نگهداری می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	61	\N	\N
234	9	U15	VegKeepRefrigerator	آیا سبزیجات را در یخچال نگهداری می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	62	\N	\N
235	9	U16	VegKeepFreezer	آیا سبزیجات را در فریزر نگهداری می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	63	\N	\N
236	9	U17	VegKeepFresh	آیا سبزیجات را به صورت تازه (بدون نگهداری) استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	64	\N	\N
237	9	U18	FreezVegTypeID	در صورت نگهداری سبزیجات در یخچال یا فریزر، آنها را به چه صورتی نگه می‌دارید؟	Categorical	{"1": "خام", "2": "آب پز شده", "3": "سرخ شده"}	\N	\N	t	65	\N	\N
238	9	U19	FreezMeatTypeID	مواد گوشتی را در یخچال یا فریزر به چه صورتی نگه می‌دارید؟	Categorical	{"1": "خام", "2": "آب پز شده", "3": "سرخ شده", "4": "نگهداری نمی‌کنم (فقط تازه استفاده می‌کنم)"}	\N	\N	t	66	\N	\N
239	9	U41	SpicyFoodIntID	چند وقت یکبار غذاهای تند مصرف می‌کنید؟ (فلفل قرمز یا سیاه)	Categorical	{"0": "هرگز", "1": "کمتر از ۱ بار در ماه", "2": "۱-۳ بار در هفته", "3": "روزانه"}	\N	\N	t	67	\N	\N
243	7	O19	HasBreastScreening	آیا سابقه غربالگری سرطان پستان یا دهانه رحم داشته‌اید؟	Categorical	{"0": "خیر", "1": "بله", "2": "نمی‌دانم"}	\N	\N	t	21	\N	\N
244	7	O20	LastMammogramAge	سن در زمان آخرین ماموگرافی:	Discrete	\N	سال	\N	t	22	\N	\N
245	7	O22	HasPapSmear	آیا سابقه پاپ اسمیر داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	24	\N	\N
246	7	O24	HasMenopause	آیا یائسه شده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	26	\N	\N
247	7	O25	MenopauseAge	سن یائسگی:	Discrete	\N	سال	\N	t	27	\N	\N
248	7	O26	NaturalMenopause	آیا یائسگی طبیعی بوده است؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	28	\N	\N
249	7	Ob1	HormoneFromAge	سن شروع مصرف داروهای جایگزین هورمونی:	Discrete	\N	سال	\N	t	29	\N	\N
250	7	Ob3	HormoneName	نوع داروی هورمونی:	Characteristic	\N	\N	\N	t	31	\N	\N
251	7	K109	HasPregnancyHypertension	آیا در دوران بارداری به فشار خون بالا (پره اکلامپسی/اکلامپسی) مبتلا شده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	17	\N	\N
252	7	K112	HasPregnancyDiabetes	آیا در دوران بارداری به دیابت بارداری مبتلا شده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	19	\N	\N
253	8	P1	HasHairLoss	آیا ریزش مو دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	6	\N	\N
256	8	P5	HasAmputationOrDisability	آیا هرگونه نقص عضو یا ناتوانی دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	9	\N	\N
257	8	P6	HasSpineDisorder	آیا اختلال ستون فقرات دارید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	10	\N	\N
260	4	L2	HasSwelling	آیا تاکنون ورم یا ادم در هر قسمت از بدن (مخصوصاً پاها) داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	41	\N	\N
263	4	L18	HasCough	آیا در یک سال گذشته حداقل به مدت ۲ هفته سرفه داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	44	\N	\N
264	4	L20	HasWheezing	آیا در یک سال گذشته حداقل به مدت ۲ هفته تنگی نفس به همراه خس خس سینه داشته‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	45	\N	\N
265	4	L23	HasHeadTrauma	آیا تاکنون ضربه به سر داشته‌اید که برای مدتی (هرچند کم) بیهوش شوید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	46	\N	\N
269	4	L27	HasFallHistory	در طول سال گذشته چند بار زمین خورده‌اید؟	Discrete	\N	بار	\N	t	50	\N	\N
284	2	D9	HeatingSystemID	سیستم گرمایش:	Categorical	{"1": "بخاری برقی", "2": "بخاری دارای دودکش", "3": "شومینه", "4": "بخاری بدون دودکش/بخاری نفتی", "5": "بخاری گازی", "6": "سایر", "7": "سیستم گرمایشی وجود ندارد"}	\N	\N	t	31	\N	\N
214	9	U22	WaterContainerTypeID1	از چه نوع ظروفی برای نگهداری آب استفاده می‌کنید؟	MultiSelect	{"1": "پلاستیکی", "2": "استیل", "3": "چینی", "4": "شیشه‌ای", "5": "سایر"}	\N	\N	t	42	\N	\N
158	4	L53	HasTransfusion	آیا سابقه ترانسفیوژن (تزریق خون) داشته‌اید؟	Categorical	{"0": "خیر", "1": "بله", "2": "نمی‌دانم"}	\N		t	38	\N	\N
100	12	Q1	BrushingNoID	دفعات مسواک زدن دندان‌ها:	Categorical	{"1": "یک بار در روز", "2": "دو بار در روز", "3": "سه بار در روز", "4": "مسواک نمی‌زنم", "5": "دندان مصنوعی دارم"}	\N		t	1	\N	\N
198	3	EA3	AnimalContactLevelTypeID	سطح تماس با حیوانات:	Categorical	{"0": "تماس با حیوانات ندارم", "1": "بعضی مواقع (محل نگهداری حیوانات در ۲۰۰ متری محل کار یا زندگی)", "2": "حداقل یک بار در دو هفته ولی کمتر از یک بار در روز", "3": "تماس روزانه (نگهداری حیوانات در محل کار یا زندگی)", "4": "تماس روزانه و نزدیک (شغل‌های مربوط به تغذیه و تمیز کردن حیوانات)"}	\N	\N	t	21	\N	\N
124	13	R6	SmokingNo	به طور متوسط چند بار در شبانه‌روز سیگار می‌کشید؟		\N	بار		t	7	\N	{"logic": "all", "rules": [{"v_code": "R5", "values": ["1"]}]}
6	1	A24	MaritalStatusID	وضعیت تأهل:	Categorical	{"1": "مجرد", "2": "متأهل", "3": "همسر مرحوم", "4": "مطلقه"}	\N		t	10	\N	\N
7	1	A28	FamilyMarriageID	آیا ازدواج فامیلی بوده است؟	Categorical	{"1": "بله، فامیل درجه یک", "2": "خیر", "3": "بله، فامیل درجه دو"}	\N		t	13	\N	{"logic": "all", "rules": [{"v_code": "A24", "values": ["2", "3", "4"]}]}
114	12	Q6	HasOralLesion	آیا ضایعه یا زخمی در دهان وجود دارد؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	7	\N	\N
115	12	Q7	UseFlossing	آیا از نخ دندان استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	8	\N	\N
119	12	Q12	UseMouthwash	آیا از دهانشویه استفاده می‌کنید؟	Dichotomous	{"0": "خیر", "1": "بله"}	\N		t	10	\N	\N
118	12	Q10	FromWhenDentures	از چه سنی دندان مصنوعی دارید؟	Discrete	\N	سالگی		t	2	\N	{"logic": "all", "rules": [{"v_code": "Q1", "values": ["5"]}]}
241	9	U45	WhyUseHerbal	دلیل استفاده از گیاه دارویی:	Characteristic	\N	\N	\N	t	70	herbal	\N
128	13	R12	UseNonCigTobacco	آیا تاکنون از محصولات دخانی غیر سیگار (ناس، قلیان، چپق) استفاده کرده‌اید؟	Dichotomous	{"0": "خیر", "1": "بله"}			t	13	\N	\N
127	13	R11	SmokeInWorkplaceID	آیا در محل کار در تماس با دود سیگار هستید؟	Categorical	{"1": "بله", "2": "خیر"}			t	11	\N	\N
125	13	R7	StopSmokingAge	از چه سنی سیگار کشیدن روزانه را متوقف کرده‌اید؟		\N	سالگی		t	8	\N	{"logic": "all", "rules": [{"v_code": "R5", "values": ["0"]}]}
120	13	R2	SmokeCigaretteTypeID	آیا در طول زندگی حداقل ۱۰۰ نخ سیگار کشیده‌اید؟	Categorical	{"1": "بله", "2": "خیر"}	\N		t	3	\N	{"logic": "all", "rules": [{"v_code": "R1", "values": ["1"]}]}
3	1	A4	GenderID	جنسیت شما چیست؟	Categorical	{"1": "مرد", "2": "زن"}	\N		t	3	\N	[null]
285	14	R13	UseDrugs	آیا تاکنون از مواد مخدر استفاده کرده‌اید؟\t	Dichotomous	{"0": "خیر", "1": "بله"}			t	1	\N	[null]
286	14	R14	UseAlcohol	آیا تاکنون از مشروبات الکلی استفاده کرده‌اید؟\t	Dichotomous	{"0": "خیر", "1": "بله"}			t	4	\N	[null]
287	13	R1	EverSmoked	آیا تا کنون سیگار کشیده اید؟	Dichotomous	{"0": "خیر", "1": "بله"}			t	2	\N	[null]
29	6	N1	DiseaseHxID	سابقه بیماری فامیلی:	MultiSelect	{"1": "دیابت", "2": "فشار خون", "3": "بیماری قلبی", "4": "سکته قلبی", "5": "سکته مغزی", "6": "سرطان معده", "7": "سرطان کولورکتال", "8": "سرطان پستان", "9": "سرطان پروستات", "10": "سرطان پوست", "11": "سرطان مثانه", "12": "سرطان سیستم خونی", "13": "سرطان مری", "14": "سرطان ریه", "15": "سرطان مغز", "16": "صرع", "17": "اختلالات روانپزشکی", "18": "سردرد مزمن", "19": "آلزایمر", "20": "شکستگی لگن", "21": "سرطان حنجره", "22": "سرطان زبان", "23": "سرطان رحم", "24": "سرطان تخمدان", "25": "لوپوس", "26": "ام اس", "27": "هیچ کدام"}	\N		t	1	\N	\N
254	8	P3	FacialHirsutism	آیا رویش موهای زائد صورت دارید؟ (فقط برای زنان)	Dichotomous	{"0": "خیر", "1": "بله"}	\N	\N	t	7	\N	{"logic": "all", "rules": [{"v_code": "A4", "values": ["2"]}]}
273	2	F2	IncomeSourceList	منبع اصلی درآمد:	MultiSelect	{"1": "بیمه", "2": "خود فرد", "3": "همسر", "4": "فرزندان", "5": "کمیته امداد / بهزیستی", "6": "پدر و مادر", "7": "سایر"}	\N	\N	t	19	\N	\N
259	4	L1	SymptomsList	کدام یک از علائم زیر تاکنون در شما تشخیص داده شده است؟ (می‌توانید چند گزینه انتخاب کنید)	MultiSelect	{"0": "هیچکدام", "1": "رفلاکس اسید معده (GERD)", "2": "نفخ و اتساع شکم", "3": "دفع خون تازه در مدفوع", "4": "کاهش وزن ناخواسته (بدون رژیم و بیش از ۵ کیلوگرم در یک ماه)", "5": "زردی چشم یا پوست بدن", "6": "شکستگی", "7": "پوکی استخوان", "8": "کمردرد", "9": "حملات تکرار شونده سردرد", "10": "حملات سرگیجه", "11": "تغییر رنگ ادرار", "12": "مشکلات ادراری (سوزش، تکرر ادرار، شب ادراری، بی اختیاری)", "13": "احساس سوزش، درد، فشار یا ناراحتی در قفسه سینه هنگام راه رفتن سریع یا سربالایی", "14": "وزوز گوش"}	\N	\N	t	40	\N	\N
11	2	C5	AccessList	کدام یک از موارد زیر را در اختیار دارید؟ (می‌توانید چند گزینه انتخاب کنید)	MultiSelect	{"0": "هیچکدام", "1": "فریزر جداگانه", "2": "ماشین لباسشویی", "3": "ماشین ظرفشویی", "4": "رایانه/لپ‌تاپ", "5": "دسترسی به اینترنت", "6": "موتورسیکلت", "7": "خودرو سواری"}	\N		t	5	\N	\N
280	2	F9	JobName	نوع شغل خود را نام ببرید:	Characteristic	\N	\N	\N	t	26	\N	{"logic": "any", "rules": [{"v_code": "F2", "values": ["1", "2"]}]}
288	4	K1	DiseaseList	کدام یک از بیماری‌های زیر تاکنون در شما تشخیص داده شده است؟ (می‌توانید چند گزینه انتخاب کنید)	MultiSelect	{"0": "هیچکدام", "1": "دیابت", "2": "فشار خون", "3": "ایسکمیک قلبی (نارسایی قلبی، آنژین)", "4": "سکته قلبی", "5": "سکته مغزی", "6": "نارسایی کلیه", "7": "کبد چرب", "8": "هپاتیت نوع B", "9": "هپاتیت نوع C", "10": "ریوی (سل/آسم)", "11": "تیروئید", "12": "سنگ کلیه", "13": "سنگ کیسه صفرا", "14": "روماتیسم", "15": "سرطان پوست", "16": "سرطان پستان", "17": "کولورکتال", "18": "سرطان سیستم هماتوپوئیتیک", "19": "سرطان پروستات", "20": "سرطان ریه", "21": "سرطان مغز و اعصاب مرکزی", "22": "سرطان معده", "23": "سرطان مری", "24": "پوکی استخوان"}	\N	\N	t	1	\N	{"logic": "any", "rules": [{"v_code": "A4", "values": ["1"], "deactive_options": []}, {"v_code": "A4", "values": ["2"], "deactive_options": ["19"]}]}
\.


--
-- TOC entry 5000 (class 0 OID 17412)
-- Dependencies: 228
-- Data for Name: responses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.responses (response_id, submission_id, question_id, v_code, is_voice, transcript, extracted_value, extracted_value_json, ai_confidence, processed_at, group_index) FROM stdin;
517	59	33	E4	f	\N	N/A	\N	\N	2026-09-02 04:17:20.094618+03:30	\N
518	59	34	H1	f	\N	4	\N	\N	2026-09-02 04:17:20.095696+03:30	\N
519	59	35	H2	f	\N	00	\N	\N	2026-09-02 04:17:20.096725+03:30	\N
520	59	24	H3	f	\N	20	\N	\N	2026-09-02 04:17:20.097694+03:30	\N
521	59	25	H4	f	\N	11	\N	\N	2026-09-02 04:17:20.099688+03:30	\N
522	59	26	H5	f	\N	00	\N	\N	2026-09-02 04:17:20.100685+03:30	\N
523	59	27	H8	f	\N	1	\N	\N	2026-09-02 04:17:20.10268+03:30	\N
524	59	28	H9	f	\N	60	\N	\N	2026-09-02 04:17:20.104658+03:30	\N
525	59	178	H10	f	\N	1	\N	\N	2026-09-02 04:17:20.105889+03:30	\N
526	59	30	H13	f	\N	0	\N	\N	2026-09-02 04:17:20.106492+03:30	\N
527	59	31	H14	f	\N	0	\N	\N	2026-09-02 04:17:20.108489+03:30	\N
528	59	32	I1	f	\N	1	\N	\N	2026-09-02 04:17:20.109486+03:30	\N
529	59	36	I2	f	\N	12	\N	\N	2026-09-02 04:17:20.110964+03:30	\N
530	59	37	J1	f	\N	0	\N	\N	2026-09-02 04:17:20.111573+03:30	\N
531	59	38	J2	f	\N	N/A	\N	\N	2026-09-02 04:17:20.112572+03:30	\N
532	59	39	J3	f	\N	1	\N	\N	2026-09-02 04:17:20.114749+03:30	\N
533	59	179	J11	f	\N	0	\N	\N	2026-09-02 04:17:20.115366+03:30	\N
534	59	40	J35	f	\N	1	\N	\N	2026-09-02 04:17:20.116365+03:30	\N
535	59	198	EA3	f	\N	4	\N	\N	2026-09-02 04:17:20.119385+03:30	\N
536	59	199	EA4	f	\N	1,2,3,4,5,6	\N	\N	2026-09-02 04:17:20.120383+03:30	\N
650	59	166	B1	f	\N	180	\N	\N	2026-09-02 04:17:20.121352+03:30	\N
651	59	167	B2	f	\N	60	\N	\N	2026-09-02 04:17:20.123347+03:30	\N
702	65	29	N1	f	\N	2	\N	\N	2026-09-02 04:27:11.514525+03:30	\N
703	65	73	N3	f	\N	1,2,9	\N	\N	2026-09-02 04:27:11.51652+03:30	\N
1023	72	168	A8	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1024	72	4	A5	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1025	72	2	A3	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1026	72	112	Q4	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1027	72	176	C23	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1028	72	255	P4	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1029	72	272	F1	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1030	72	281	D6	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1031	72	282	D7	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1032	72	283	D8	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1033	72	39	J3	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1034	72	40	J35	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1035	72	8	A30	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1036	72	9	C1	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1037	72	10	C4	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1038	72	19	C24	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1039	72	20	C25	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1040	72	21	C26	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1041	72	22	E1	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1042	72	24	H3	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1043	72	25	H4	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1044	72	26	H5	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1045	72	27	H8	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1046	72	30	H13	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1047	72	31	H14	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1048	72	32	I1	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1049	72	34	H1	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1050	72	35	H2	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1051	72	37	J1	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1052	72	90	B3	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
652	59	90	B3	f	\N	72	\N	\N	2026-09-02 04:17:20.124385+03:30	\N
653	59	91	B4	f	\N	88	\N	\N	2026-09-02 04:17:20.125408+03:30	\N
654	59	101	B5	f	\N	14	\N	\N	2026-09-02 04:17:20.126989+03:30	\N
655	59	253	P1	f	\N	1	\N	\N	2026-09-02 04:17:20.127601+03:30	\N
656	59	255	P4	f	\N	2	\N	\N	2026-09-02 04:17:20.128601+03:30	\N
657	59	256	P5	f	\N	0	\N	\N	2026-09-02 04:17:20.130743+03:30	\N
658	59	257	P6	f	\N	0	\N	\N	2026-09-02 04:17:20.131982+03:30	\N
659	59	258	P7	f	\N	N/A	\N	\N	2026-09-02 04:17:20.133211+03:30	\N
660	59	102	G1	f	\N	7	\N	\N	2026-09-02 04:17:20.134212+03:30	\N
661	59	103	G2	f	\N	2	\N	\N	2026-09-02 04:17:20.136853+03:30	\N
662	59	104	G4	f	\N	4	\N	\N	2026-09-02 04:17:20.138143+03:30	\N
663	59	105	G5	f	\N	0	\N	\N	2026-09-02 04:17:20.139143+03:30	\N
664	59	106	G8	f	\N	1	\N	\N	2026-09-02 04:17:20.140655+03:30	\N
665	59	107	G11	f	\N	1	\N	\N	2026-09-02 04:17:20.141274+03:30	\N
666	59	108	G12	f	\N	1	\N	\N	2026-09-02 04:17:20.14327+03:30	\N
667	59	109	G14	f	\N	1	\N	\N	2026-09-02 04:17:20.144269+03:30	\N
668	59	93	G18	f	\N	0	\N	\N	2026-09-02 04:17:20.145265+03:30	\N
669	59	94	G21	f	\N	0	\N	\N	2026-09-02 04:17:20.14726+03:30	\N
670	59	96	G23	f	\N	0	\N	\N	2026-09-02 04:17:20.148258+03:30	\N
671	59	95	G22	f	\N	0	\N	\N	2026-09-02 04:17:20.149283+03:30	\N
672	59	100	Q1	f	\N	1	\N	\N	2026-09-02 04:17:20.150252+03:30	\N
673	59	118	Q10	f	\N	N/A	\N	\N	2026-09-02 04:17:20.153084+03:30	\N
674	59	110	Q2	f	\N	32	\N	\N	2026-09-02 04:17:20.154406+03:30	\N
675	59	111	Q3	f	\N	6	\N	\N	2026-09-02 04:17:20.155639+03:30	\N
1053	72	91	B4	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1054	72	93	G18	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1055	72	94	G21	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1056	72	95	G22	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1057	72	96	G23	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1058	72	101	B5	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1059	72	102	G1	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1060	72	103	G2	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1061	72	104	G4	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1062	72	105	G5	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1063	72	106	G8	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1064	72	107	G11	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1065	72	108	G12	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1066	72	109	G14	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1067	72	110	Q2	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1068	72	111	Q3	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1069	72	113	Q5	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1070	72	166	B1	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
515	59	22	E1	f	\N	1	\N	\N	2026-09-02 04:17:20.092151+03:30	\N
516	59	23	E3	f	\N	N/A	\N	\N	2026-09-02 04:17:20.093395+03:30	\N
676	59	112	Q4	f	\N	0	\N	\N	2026-09-02 04:17:20.156868+03:30	\N
677	59	113	Q5	f	\N	4	\N	\N	2026-09-02 04:17:20.158105+03:30	\N
678	59	114	Q6	f	\N	0	\N	\N	2026-09-02 04:17:20.159105+03:30	\N
679	59	115	Q7	f	\N	0	\N	\N	2026-09-02 04:17:20.160101+03:30	\N
680	59	116	Q8	f	\N	N/A	\N	\N	2026-09-02 04:17:20.162097+03:30	\N
681	59	119	Q12	f	\N	1	\N	\N	2026-09-02 04:17:20.163109+03:30	\N
1071	72	167	B2	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1072	72	169	A10	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1073	72	170	A20	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1074	72	171	A21	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1075	72	172	A22	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1076	72	174	C2	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1077	72	175	C3	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1078	72	177	C27	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1079	72	178	H10	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1080	72	179	J11	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1081	72	253	P1	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1082	72	256	P5	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1083	72	257	P6	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1084	72	284	D9	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1085	72	100	Q1	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1086	72	198	EA3	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1087	72	6	A24	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1088	72	114	Q6	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1089	72	115	Q7	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1090	72	119	Q12	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1091	72	3	A4	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1092	72	273	F2	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1093	72	11	C5	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1094	72	258	P7	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1095	72	36	I2	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1096	72	28	H9	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1097	72	38	J2	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1098	72	116	Q8	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1099	72	199	EA4	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1100	72	280	F9	t	\N	1	\N	\N	2026-09-02 04:55:08.482892+03:30	\N
1101	72	5	A26	f	\N	N/A	\N	\N	2026-09-02 04:55:08.640376+03:30	\N
1102	72	33	E4	f	\N	N/A	\N	\N	2026-09-02 04:55:08.640376+03:30	\N
1103	72	23	E3	f	\N	N/A	\N	\N	2026-09-02 04:55:08.640376+03:30	\N
1104	72	190	A27	f	\N	N/A	\N	\N	2026-09-02 04:55:08.640376+03:30	\N
306	59	6	A24	f	\N	1	\N	\N	2026-09-02 04:17:20.06164+03:30	\N
307	59	5	A26	f	\N	N/A	\N	\N	2026-09-02 04:17:20.062832+03:30	\N
308	59	190	A27	f	\N	N/A	\N	\N	2026-09-02 04:17:20.063831+03:30	\N
309	59	7	A28	f	\N	N/A	\N	\N	2026-09-02 04:17:20.064828+03:30	\N
310	59	8	A30	f	\N	1	\N	\N	2026-09-02 04:17:20.066849+03:30	\N
311	59	9	C1	f	\N	1	\N	\N	2026-09-02 04:17:20.068819+03:30	\N
312	59	174	C2	f	\N	120	\N	\N	2026-09-02 04:17:20.070608+03:30	\N
313	59	175	C3	f	\N	3	\N	\N	2026-09-02 04:17:20.071896+03:30	\N
314	59	10	C4	f	\N	5	\N	\N	2026-09-02 04:17:20.072896+03:30	\N
537	63	168	A8	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
538	63	4	A5	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
539	63	2	A3	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
540	63	112	Q4	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
541	63	176	C23	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
542	63	255	P4	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
543	63	272	F1	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
544	63	281	D6	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
545	63	282	D7	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
546	63	283	D8	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
547	63	39	J3	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
548	63	40	J35	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
549	63	8	A30	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
550	63	9	C1	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
551	63	10	C4	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
552	63	19	C24	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
553	63	20	C25	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
554	63	21	C26	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
555	63	22	E1	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
556	63	24	H3	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
557	63	25	H4	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
558	63	26	H5	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
559	63	27	H8	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
560	63	30	H13	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
561	63	31	H14	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
562	63	32	I1	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
563	63	34	H1	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
564	63	35	H2	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
565	63	37	J1	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
566	63	90	B3	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
567	63	91	B4	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
568	63	93	G18	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
569	63	94	G21	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
570	63	95	G22	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
571	63	96	G23	t	\N	1	\N	\N	2026-09-02 03:55:09.403905+03:30	\N
315	59	11	C5	f	\N	0,1,2,3,4,5,6,7	\N	\N	2026-09-02 04:17:20.074394+03:30	\N
316	59	176	C23	f	\N	1	\N	\N	2026-09-02 04:17:20.075394+03:30	\N
317	59	19	C24	f	\N	0	\N	\N	2026-09-02 04:17:20.076891+03:30	\N
318	59	20	C25	f	\N	0	\N	\N	2026-09-02 04:17:20.078135+03:30	\N
319	59	21	C26	f	\N	0	\N	\N	2026-09-02 04:17:20.079376+03:30	\N
320	59	177	C27	f	\N	0	\N	\N	2026-09-02 04:17:20.079846+03:30	\N
321	59	272	F1	f	\N	1	\N	\N	2026-09-02 04:17:20.081842+03:30	\N
322	59	273	F2	f	\N	1,2,3,4,5,6,7	\N	\N	2026-09-02 04:17:20.083169+03:30	\N
323	59	280	F9	f	\N	مکانیک	\N	\N	2026-09-02 04:17:20.084806+03:30	\N
324	59	281	D6	f	\N	3	\N	\N	2026-09-02 04:17:20.087109+03:30	\N
325	59	283	D8	f	\N	4	\N	\N	2026-09-02 04:17:20.088395+03:30	\N
326	59	284	D9	f	\N	7	\N	\N	2026-09-02 04:17:20.088869+03:30	\N
327	59	282	D7	f	\N	4	\N	\N	2026-09-02 04:17:20.090865+03:30	\N
682	65	288	K1	f	\N	N/A	\N	\N	2026-09-02 04:27:11.487942+03:30	\N
683	65	148	L6	f	\N	0	\N	\N	2026-09-02 04:27:11.488911+03:30	\N
684	65	149	L7	f	\N	N/A	\N	\N	2026-09-02 04:27:11.490906+03:30	\N
685	65	158	L53	f	\N	0	\N	\N	2026-09-02 04:27:11.491931+03:30	\N
686	65	159	L55	f	\N	0	\N	\N	2026-09-02 04:27:11.4929+03:30	\N
687	65	259	L1	f	\N	13	\N	\N	2026-09-02 04:27:11.493908+03:30	\N
688	65	260	L2	f	\N	0	\N	\N	2026-09-02 04:27:11.495892+03:30	\N
689	65	263	L18	f	\N	1	\N	\N	2026-09-02 04:27:11.496908+03:30	\N
690	65	264	L20	f	\N	0	\N	\N	2026-09-02 04:27:11.497911+03:30	\N
1105	72	7	A28	f	\N	N/A	\N	\N	2026-09-02 04:55:08.640376+03:30	\N
1106	72	118	Q10	f	\N	N/A	\N	\N	2026-09-02 04:55:08.640376+03:30	\N
1107	72	254	P3	f	\N	N/A	\N	\N	2026-09-02 04:55:08.640376+03:30	\N
1108	73	69	Ma2	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1109	73	70	Ma3	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1110	73	71	Ma4	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1111	73	270	L51	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1112	73	289	M4	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1113	73	159	L55	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
297	59	2	A3	f	\N	17	\N	\N	2026-09-02 04:17:20.047218+03:30	\N
298	59	3	A4	f	\N	1	\N	\N	2026-09-02 04:17:20.048243+03:30	\N
299	59	254	P3	f	\N	N/A	\N	\N	2026-09-02 04:17:20.049213+03:30	\N
300	59	4	A5	f	\N	22	\N	\N	2026-09-02 04:17:20.051208+03:30	\N
301	59	168	A8	f	\N	1	\N	\N	2026-09-02 04:17:20.054201+03:30	\N
302	59	169	A10	f	\N	1	\N	\N	2026-09-02 04:17:20.056194+03:30	\N
303	59	170	A20	f	\N	16	\N	\N	2026-09-02 04:17:20.058032+03:30	\N
304	59	171	A21	f	\N	5	\N	\N	2026-09-02 04:17:20.059259+03:30	\N
305	59	172	A22	f	\N	3	\N	\N	2026-09-02 04:17:20.060451+03:30	\N
691	65	265	L23	f	\N	0	\N	\N	2026-09-02 04:27:11.498884+03:30	\N
692	65	269	L27	f	\N	1	\N	\N	2026-09-02 04:27:11.500879+03:30	\N
693	65	270	L51	f	\N	0	\N	\N	2026-09-02 04:27:11.502874+03:30	\N
694	65	271	L52	f	\N	N/A	\N	\N	2026-09-02 04:27:11.503871+03:30	\N
695	65	289	M4	f	\N	1	\N	\N	2026-09-02 04:27:11.505867+03:30	\N
696	65	69	Ma2	f	\N	0	\N	\N	2026-09-02 04:27:11.506863+03:30	\N
697	65	70	Ma3	f	\N	0	\N	\N	2026-09-02 04:27:11.507886+03:30	\N
698	65	71	Ma4	f	\N	0	\N	\N	2026-09-02 04:27:11.508825+03:30	\N
699	65	92	M1	f	\N	کافئین	\N	\N	2026-09-02 04:27:11.511624+03:30	0
700	65	63	M3	f	\N	1	\N	\N	2026-09-02 04:27:11.512907+03:30	0
701	65	66	Ma1	f	\N	0	\N	\N	2026-09-02 04:27:11.513526+03:30	\N
1114	73	148	L6	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1115	73	260	L2	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1116	73	263	L18	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1117	73	264	L20	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1118	73	265	L23	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1119	73	269	L27	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1120	73	158	L53	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1121	73	29	N1	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1122	73	259	L1	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1123	73	271	L52	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1124	73	92	M1	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1125	73	63	M3	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1126	73	66	Ma1	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1127	73	73	N3	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1128	73	149	L7	t	\N	1	\N	\N	2026-09-02 04:55:08.759461+03:30	\N
1129	73	74	O1	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1130	73	75	O2	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1131	73	76	O3	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1132	73	77	O4	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1133	73	78	O5	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1134	73	79	O6	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1135	73	80	O7	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1136	73	81	O8	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1137	73	82	O9	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1138	73	83	O10	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1139	73	84	O11	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1140	73	85	O12	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1141	73	86	O14	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1142	73	87	O16	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1143	73	88	O17	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1144	73	89	Oa3	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1145	73	243	O19	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1146	73	244	O20	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1147	73	245	O22	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1148	73	246	O24	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1149	73	247	O25	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1150	73	248	O26	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1151	73	249	Ob1	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1152	73	250	Ob3	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1153	73	251	K109	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1154	73	252	K112	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1155	73	288	K1	f	\N	N/A	\N	\N	2026-09-02 04:55:08.845081+03:30	\N
1156	74	201	V2	f	\N	N/A	\N	\N	2026-09-02 04:55:08.900772+03:30	\N
1157	74	121	R3	f	\N	N/A	\N	\N	2026-09-02 04:55:08.900772+03:30	\N
1158	74	123	R5	f	\N	N/A	\N	\N	2026-09-02 04:55:08.900772+03:30	\N
1159	74	122	R4	f	\N	N/A	\N	\N	2026-09-02 04:55:08.900772+03:30	\N
1160	74	126	R10	f	\N	N/A	\N	\N	2026-09-02 04:55:08.900772+03:30	\N
1161	74	130	Rc3	f	\N	N/A	\N	\N	2026-09-02 04:55:08.900772+03:30	\N
1162	74	133	Rc4	f	\N	N/A	\N	\N	2026-09-02 04:55:08.900772+03:30	\N
1163	74	132	Rd3	f	\N	N/A	\N	\N	2026-09-02 04:55:08.900772+03:30	\N
1164	74	124	R6	f	\N	N/A	\N	\N	2026-09-02 04:55:08.900772+03:30	\N
1165	74	125	R7	f	\N	N/A	\N	\N	2026-09-02 04:55:08.900772+03:30	\N
1166	74	120	R2	f	\N	N/A	\N	\N	2026-09-02 04:55:08.900772+03:30	\N
1177	66	120	R2	f	\N	2	\N	\N	2026-09-02 05:10:38.995828+03:30	\N
1167	66	97	H6	f	\N	7	\N	\N	2026-09-02 05:10:38.980871+03:30	\N
1168	66	98	H7	f	\N	00	\N	\N	2026-09-02 05:10:38.983881+03:30	\N
1169	66	99	H12	f	\N	3	\N	\N	2026-09-02 05:10:38.985857+03:30	\N
1170	66	285	R13	f	\N	0	\N	\N	2026-09-02 05:10:38.986855+03:30	\N
1171	66	130	Rc3	f	\N	N/A	\N	\N	2026-09-02 05:10:38.987853+03:30	\N
1172	66	133	Rc4	f	\N	N/A	\N	\N	2026-09-02 05:10:38.988849+03:30	\N
1173	66	286	R14	f	\N	1	\N	\N	2026-09-02 05:10:38.990845+03:30	\N
1174	66	132	Rd3	f	\N	1,2,3,4	\N	\N	2026-09-02 05:10:38.992269+03:30	\N
1175	66	242	R8	f	\N	1	\N	\N	2026-09-02 05:10:38.993543+03:30	\N
1176	66	287	R1	f	\N	1	\N	\N	2026-09-02 05:10:38.994829+03:30	\N
1178	66	180	T1	f	\N	1	\N	\N	2026-09-02 05:10:38.997824+03:30	\N
\.


--
-- TOC entry 5002 (class 0 OID 17422)
-- Dependencies: 230
-- Data for Name: sections; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sections (section_id, form_id, section_key, name_fa, sort_order, depends_on_vcode, depends_on_value, skip_if_vcode, skip_if_value) FROM stdin;
1	1	identity	مشخصات فردی	1	\N	\N	\N	\N
2	1	socioeconomic	وضعیت اجتماعی اقتصادی	2	\N	\N	\N	\N
3	1	lifestyle	سبک زندگی (آب و تغذیه)	3	\N	\N	\N	\N
4	3	medical_history	سابقه بیماری‌های مزمن	4	\N	\N	\N	\N
5	3	medications	داروهای مصرفی	5	\N	\N	\N	\N
6	3	family_history	سابقه بیماری خانوادگی	6	\N	\N	\N	\N
7	3	reproductive	تاریخچه باروری (زنان)	7	A4	2	\N	\N
8	1	anthropometry	تن‌سنجی (قد و وزن)	8	\N	\N	\N	\N
9	2	nutrition_ffq	بسامد مصرف خوراک (FFQ)	9	\N	\N	\N	\N
10	1	physical_activity	فعالیت فیزیکی	10	\N	\N	\N	\N
11	2	sleep_habits	الگوی خواب	11	\N	\N	\N	\N
12	1	oral_health	بهداشت دهان و دندان	12	\N	\N	\N	\N
13	2	smoking	مصرف دخانیات	13	\N	\N	\N	\N
14	2	alcohol_drugs	الکل و مواد مخدر	14	\N	\N	\N	\N
\.


--
-- TOC entry 5004 (class 0 OID 17433)
-- Dependencies: 232
-- Data for Name: submissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.submissions (submission_id, user_id, form_id, status, created_at, updated_at) FROM stdin;
63	35	1	complete	2026-09-02 03:55:09.383853+03:30	2026-09-02 03:55:09.802655+03:30
59	27	1	complete	2026-09-02 03:28:34.023329+03:30	2026-09-02 04:17:20.163109+03:30
65	27	3	draft	2026-09-02 04:18:27.596414+03:30	2026-09-02 04:27:11.51652+03:30
72	43	1	completed	2026-09-02 04:55:08.467911+03:30	2026-09-02 04:55:08.718048+03:30
73	43	3	completed	2026-09-02 04:55:08.743004+03:30	2026-09-02 04:55:08.85802+03:30
74	43	2	draft	2026-09-02 04:55:08.879408+03:30	2026-09-02 04:55:08.912339+03:30
66	27	2	draft	2026-09-02 04:27:42.334885+03:30	2026-09-02 05:10:39.00712+03:30
\.


--
-- TOC entry 5006 (class 0 OID 17443)
-- Dependencies: 234
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, first_name, last_name, national_code, phone_number, role, created_at, email, sex, birth_date) FROM stdin;
1	امین	اسماعیلی	0123456789	09123456789	2	2026-05-24 21:00:33.379093+03:30	\N	\N	\N
22	سبحان	عسکری	4011277144	09444444444	1	2026-09-01 16:15:13.426039+03:30	kornk122@atomicmail.io	\N	\N
23	رضا	رضازاده	0123456780	09123456833	1	2026-09-01 22:26:15.745552+03:30	\N	\N	\N
27	تست	یک	4011277141	09111111111	1	2026-09-02 03:14:26.671713+03:30	\N	\N	\N
29	R	T	6666660002	\N	1	2026-09-02 03:25:17.174625+03:30	\N	\N	\N
35	B	T	4444440009	\N	1	2026-09-02 03:55:09.36831+03:30	\N	\N	\N
43	E	T	1111110009	\N	1	2026-09-02 04:55:08.42721+03:30	\N	\N	\N
\.


--
-- TOC entry 5015 (class 0 OID 0)
-- Dependencies: 221
-- Name: api_logs_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_logs_log_id_seq', 1, true);


--
-- TOC entry 5016 (class 0 OID 0)
-- Dependencies: 223
-- Name: forms_form_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.forms_form_id_seq', 3, true);


--
-- TOC entry 5017 (class 0 OID 0)
-- Dependencies: 225
-- Name: health_checks_check_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.health_checks_check_id_seq', 1, false);


--
-- TOC entry 5018 (class 0 OID 0)
-- Dependencies: 227
-- Name: questions_question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.questions_question_id_seq', 289, true);


--
-- TOC entry 5019 (class 0 OID 0)
-- Dependencies: 229
-- Name: responses_response_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.responses_response_id_seq', 1178, true);


--
-- TOC entry 5020 (class 0 OID 0)
-- Dependencies: 231
-- Name: sections_section_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sections_section_id_seq', 16, true);


--
-- TOC entry 5021 (class 0 OID 0)
-- Dependencies: 233
-- Name: submissions_submission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.submissions_submission_id_seq', 74, true);


--
-- TOC entry 5022 (class 0 OID 0)
-- Dependencies: 235
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 43, true);


--
-- TOC entry 4817 (class 2606 OID 17455)
-- Name: api_logs api_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_logs
    ADD CONSTRAINT api_logs_pkey PRIMARY KEY (log_id);


--
-- TOC entry 4819 (class 2606 OID 17457)
-- Name: forms forms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms
    ADD CONSTRAINT forms_pkey PRIMARY KEY (form_id);


--
-- TOC entry 4821 (class 2606 OID 17459)
-- Name: health_checks health_checks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.health_checks
    ADD CONSTRAINT health_checks_pkey PRIMARY KEY (check_id);


--
-- TOC entry 4823 (class 2606 OID 17461)
-- Name: health_checks health_checks_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.health_checks
    ADD CONSTRAINT health_checks_user_id_key UNIQUE (user_id);


--
-- TOC entry 4825 (class 2606 OID 17463)
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (question_id);


--
-- TOC entry 4827 (class 2606 OID 17465)
-- Name: questions questions_v_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_v_code_key UNIQUE (v_code);


--
-- TOC entry 4829 (class 2606 OID 17467)
-- Name: responses responses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responses
    ADD CONSTRAINT responses_pkey PRIMARY KEY (response_id);


--
-- TOC entry 4831 (class 2606 OID 17469)
-- Name: sections sections_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_pkey PRIMARY KEY (section_id);


--
-- TOC entry 4833 (class 2606 OID 17471)
-- Name: submissions submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_pkey PRIMARY KEY (submission_id);


--
-- TOC entry 4835 (class 2606 OID 17473)
-- Name: users users_national_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_national_code_key UNIQUE (national_code);


--
-- TOC entry 4837 (class 2606 OID 17475)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4838 (class 2606 OID 17476)
-- Name: api_logs api_logs_submission_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_logs
    ADD CONSTRAINT api_logs_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id) ON DELETE CASCADE;


--
-- TOC entry 4839 (class 2606 OID 17481)
-- Name: health_checks health_checks_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.health_checks
    ADD CONSTRAINT health_checks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4840 (class 2606 OID 17486)
-- Name: questions questions_section_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.sections(section_id) ON DELETE CASCADE;


--
-- TOC entry 4841 (class 2606 OID 17491)
-- Name: responses responses_submission_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responses
    ADD CONSTRAINT responses_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id) ON DELETE CASCADE;


--
-- TOC entry 4842 (class 2606 OID 17496)
-- Name: sections sections_form_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(form_id) ON DELETE CASCADE;


--
-- TOC entry 4843 (class 2606 OID 17501)
-- Name: submissions submissions_form_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(form_id) ON DELETE CASCADE;


--
-- TOC entry 4844 (class 2606 OID 17506)
-- Name: submissions submissions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


-- Completed on 2026-09-02 13:10:08

--
-- PostgreSQL database dump complete
--

\unrestrict n4U4PqBuA3DpvosVc0Piq8sbbN1iByze3DmfaenbK2McCSMqvU3YflIgsr86O1G

